### ISSUE TITLE
عدم کار کرد پنل بعد از چند دقیقه در اوپن وی پی ان (بدون پر شدن رم و سی پی یو )

### ISSUE THREAD

**Issue by FarhadMohseni** [radkesvat/ReverseTlsTunnel#104]
تانل انجام شده و دارم یوزر نهایی داره از اوپن وی پی ان استفاده میکنه . نزدیک 100 تا یوزر فعال هستن همیشه ؛ بعد از اجرا کردن پنل چه به صورت سرویس و چه nohup در حالت مالتی پورت  ؛ بعد از مدتی کانکشن قطع میشه . در لاگ های تانل هیچ ارور خاصی مشاهده نمیشه اما مشکل با ریستارت کردن سرور حل میشه ، و بعد از 20 دقیقه مجدد پیش میاد و باید سرور مجدد ریستارت بشه

از فلگ --pool 4 هم استفاده شده و نتیجه یکسان بود

توضیحات : دسترسی به سرور دسترسی روت هست 
چک سام در هر دو سرور ایران و خارج :
279ed15e9894a7b3a68babc6c9112c3f  RTT
(سرعت کانکشن عالیه و هیچ افتی نداره و مشکل فقط این مورد هست)
درصورت تمایل مایل به ارسال هرنوع لاگ یا فایل دیگه ای هستم

ادیت ، خروجی journalctl -xe در سرور خارج:
![image](https://github.com/radkesvat/ReverseTlsTunnel/assets/25081900/bb6c8b39-7642-4e7c-95d9-ce717ba3a313)

خروجی همین دستور در سرور ایران:
![image](https://github.com/radkesvat/ReverseTlsTunnel/assets/25081900/6d3520e5-83a9-4b45-91b0-f8479e098990)

**Comment by FarhadMohseni** [comment]
بعد از عوض کردن پورت سرور از 22 به یک پورت دیگه مشکل حل شد . این Issue رو فعلا میبندم .

**Comment by radkesvat** [comment]
اوکیه نسخه جدید هم اگه ممکنه تست کنید و نتیجه را اطلاع بدین

**Comment by Metti1374** [comment]
Kasi mitone rahnamayim kone linux tunell konm ba ibs
