### ISSUE TITLE
اتصال چند سرور خارج به یک سرور ایران

### ISSUE THREAD

**Issue by majiix** [radkesvat/ReverseTlsTunnel#110]
سلام. ممنون از زحماتتون. آیا امکانش هست چند سرور خارج رو به یک سرور ایران متصل کنیم؟

**Comment by radkesvat** [comment]
بله در لودبالنسر آخر مطلب کامل توضیح دادم


https://github.com/radkesvat/ReverseTlsTunnel/blob/master/Loadbalancer.md
