### ISSUE TITLE
مشکل در نصب نسخه آخر

### ISSUE THREAD

**Issue by majiix** [radkesvat/ReverseTlsTunnel#111]
فکر میکنم بخاطر اینکه عدد فارسی تو ریلیز نسخه آخر خورده V4.۲ سرور خطا میده.
https://github.com/radkesvat/ReverseTlsTunnel/releases/tag/V4.%DB%B2

**Comment by radkesvat** [comment]
اخ اخ امان از اشتباهات تایپی 😅

ممنون که اطلاع دادین
