### ISSUE TITLE
لطفاً بگید چجوری میشه ورژن های قبلی رو نصب کنم

### ISSUE THREAD

**Issue by ramtiny** [radkesvat/ReverseTlsTunnel#129]
سلام و خسته نباشید
با ورژن ۴٫۶ مشکلی که هست یهو قطع میشه تانل
لطفا بگید چجوری میتونم برم ورژن های قبلی مثل ورژن ۳٫۳
ممنون بابت پاسخگویی

**Comment by radkesvat** [comment]
داخل گیت هاب بخه release ها تمام نسخه ها فایل زیپش هست

**Comment by radkesvat** [comment]
https://github.com/radkesvat/ReverseTlsTunnel/releases/tag/V3.3

**Comment by m2tts2001** [comment]
دستورات زیر رو به ترتیب انجام بدید
من به عنوان مثال نسخه 3.6 رو میگم
wget "https://github.com/radkesvat/ReverseTlsTunnel/releases/download/V3.6/v3.6_linux_amd64.zip"
unzip https://github.com/radkesvat/ReverseTlsTunnel/releases/download/V3.6/v3.6_linux_amd64.zip
chmod +x RTT

الان عملا نسخه 3.6 رو دارید. هنگام ان زیپ کردن ازتون اجازه میخواد که y رو میزنید.
قبل از اینکه مراحل رو انجام بدید بهتره سرویس رو غیر فعال کنید و بعدش pkill RTT رو بزنید
systemctl stop tunnel.service
pkill RTT
بعد از نصب ورژن 3.6 با دستور زیر راه اندازی میشه
systemctl start tunnel.service

**Comment by ramtiny** [comment]
من این دستور رو میزنم همیشه
bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/FakeTlsTunnel/master/FtTunnel.sh)

الان بجای این دستور باید چه دستوری بزنم

bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/FakeTlsTunnel/master/FtTunnel.sh) 3.3

مثلا ۳٫۳ رو نباید اخرش بنویسم؟

**Comment by m2tts2001** [comment]
> من این دستور رو میزنم همیشه bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/FakeTlsTunnel/master/FtTunnel.sh)
> 
> الان بجای این دستور باید چه دستوری بزنم
> 
> bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/FakeTlsTunnel/master/FtTunnel.sh) 3.3
> 
> مثلا ۳٫۳ رو نباید اخرش بنویسم؟

تا اونجایی که من میدونم شما دستور نصب تونل مستقیم رو نوشتید. در حالی که روش جدید مهندس تونل معکوس هست. این دوتا جدا از هم هستند شما کافیه RTT رو غیر فعال و FTT رو نصب و استفاده کنید.
RTT= reverse tls tunnel
FTT= fake tls tunnel

**Comment by ramtiny** [comment]
بله منظورم این دستور هست
bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/ReverseTlsTunnel/main/RtTunnel.sh)

من چیکار کنم بجای این دستور انتهاش بزنم ۳.۳ ورزن ۳٫۳ نصب نمیشه؟
bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/ReverseTlsTunnel/main/RtTunnel.sh) ۳.۳

**Comment by radkesvat** [comment]
این فیلمو ببینید ؛ سازده فیلم از یه اسکریپت استفاده کرده که نسخه 3.6 رو نصب میکنه ؛ احتمالا اون نسخه رو میخواید 

https://www.youtube.com/watch?v=E5oyiKVSERE

**Comment by ramtiny** [comment]
> این فیلمو ببینید ؛ سازده فیلم از یه اسکریپت استفاده کرده که نسخه 3.6 رو نصب میکنه ؛ احتمالا اون نسخه رو میخواید
> 
> https://www.youtube.com/watch?v=E5oyiKVSERE

اره دقیقاً من میخوام از طریق اسکریپت نسخه ۳٫۶ رو نصب کنم

**Comment by ramtiny** [comment]
باید از طریق پیج گیت هاب سازنده اسکریپت ازش بخوام نسخه ۳٫۶ رو دستورشو بفرسته؟

**Comment by radkesvat** [comment]
خودش دیفالت 3.6 نصب میکنه دوست عزیز

**Comment by ramtiny** [comment]
بله تشکر 
البته سازنده اون اسکریپت هم بصورت دیفالت ابتدای نصب از ما ورژن رو میپرسه
خیلی خوب شد

**Comment by radkesvat** [comment]
service tunnel stop
