### ISSUE TITLE
بررسی تداخل با sing-box

### ISSUE THREAD

**Issue by AkramiPro** [radkesvat/ReverseTlsTunnel#133]
سلام مهندس خسته نباشی
یه سوال فنی داشتم . الان من از sing-box استفاده میکنم که از mux پشتیبانی میکنه
من داخل nekobox رفتم mux رو روی 16 تنظیم کردم و حالت smux 
برای تانل هم mux رو 16 تنظیم کردم 
همه چی داره درست کار میکنه ولی در کل خواستم سوال کنم که ایا اینکه هر 2 تاشون دارن mux میکنن مشکلی پیش نمیاره ؟

**Comment by radkesvat** [comment]
نه ولی این حرکت خیلی جابتی نیست پردازش زیاد میبره و طول پکت ها زیاد میشن سرعت هم طبیعتا کم میشه
یه جا ماکس اتفاق بیفته کافیه

**Comment by AkramiPro** [comment]
حله ممنون
