### ISSUE TITLE
قطع تانل

### ISSUE THREAD

**Issue by siavash3441** [radkesvat/ReverseTlsTunnel#136]
سلام یک ساعته تمامی تانل ها قطع شدن حتی با دیتا سنتر دیگه ایرانی هم می زنم کانکت نمیشه

**Comment by siavash3441** [comment]
حل شد داداش

**Comment by radkesvat** [comment]
اپدیت کنید حتما نسخه اخر

**Comment by RezaKardoost** [comment]
من دیشب از نسخه 4.6 به 5 اپدیت کردم و فعلا قطع و وصلی نداشتم. صرفا خواستم گزارش بدم. ممنون بابت پیگیری هاتون. شرایط رو واسمون راحت تر میکنید

**Comment by siavash3441** [comment]
فقط با فعال شدن mux تانل قطع میشه چند تا دیتا سنتر امتحان کردم

**Comment by radkesvat** [comment]
بعیده به خاطر ماکس باشه ولی من و دوستان فعلا امروز بدون ماکس تست کردیم و فردا با ماکس تست میشه
