### ISSUE TITLE
 ipv6: ارور در سرور خارج با نسخه جدید با ای پی ورژن6

### ISSUE THREAD

**Issue by Hamed-F** [radkesvat/ReverseTlsTunnel#145]
سلام 
چون هم سرور خارج هم ایران ipv6 داشتم امدم و گفتم تست کنم ببینم کار میکنه یا نه
دقیقا مثل مثال شما رفتم و همه چی رو ست کردم
همچنین برای محکم کار هم از سرور ایران هم سرور خارج ipv6 هم دیگه رو پینگ کردم و اکی بودن
اما نشد و این ارور رو در سرور خارج به من داد

Oct 01 00:13:39 greasy RTT[8857]: Mode Foreign Server:  xx.xxx.xxx.xx <-> [xxxx:xxxx:x:x:x:xxx:xxxx:1] (myket.ir with ip 176.65.2>
Oct 01 00:13:39 greasy RTT[8857]: Connection failed because:
Oct 01 00:13:39 greasy RTT[8857]: TransportAddressError: Invalid IP Address. Address contains an invalid character
Oct 01 00:13:39 greasy RTT[8857]: Connection failed because:
Oct 01 00:13:39 greasy RTT[8857]: TransportAddressError: Invalid IP Address. Address contains an invalid character
Oct 01 00:13:44 greasy RTT[8857]: free: 0  iran: 0 core: 0
Oct 01 00:13:44 greasy RTT[8857]: Connection failed because:
Oct 01 00:13:44 greasy RTT[8857]: TransportAddressError: Invalid IP Address. Address contains an invalid character
Oct 01 00:13:44 greasy RTT[8857]: Connection failed because:
Oct 01 00:13:44 greasy RTT[8857]: TransportAddressError: Invalid IP Address. Address contains an invalid character

**Comment by radkesvat** [comment]
سلام

**Comment by radkesvat** [comment]
داخل 
--iran-ip


ایپی سرور ایران روبدون براکت قرار بدین

**Comment by Hamed-F** [comment]
باز هم ارور داد :))
سرور سمت ایران دفعه پیش با --peer: به ای پی اشاره میکردم ارور میداد چون داخل براکت گذاشته بودم ای پی رو که الان بدون براکت گذاشتم اکی شد
اما سمت خارج دوباره ارور دیگه ای انگار میده:
Oct 01 01:04:03 greasy RTT[10026]: Connection failed because:
Oct 01 01:04:03 greasy RTT[10026]: TransportOsError: (111) Connection refused
Oct 01 01:04:03 greasy RTT[10026]: Connection failed because:
Oct 01 01:04:03 greasy RTT[10026]: TransportOsError: (111) Connection refused

**Comment by radkesvat** [comment]
مشکل از خارج نیست ؛ خارج میخواد به ایران وصل بشه اما نمیتونه یا ایران روشن نیست تونل یا پورت اش مغایرت داره یا پورت بسته هست شاید فایروال فعاله

**Comment by Hamed-F** [comment]
به نظر میاد مشکل اینجاست که میخواد با ipv4 به ipv6 ایران متصل بشه به جای اینکه بیاد با ipv6 به ipv6 متصل بشه؟


Oct 01 01:25:37 greasy- RTT[11442]: Mode Foreign Server:  xx.xxx.xxx.xx <-> xxxx:xxxx❌x❌xxx:xxxx:1 (myket.ir with ip 18>
Oct 01 01:25:37 greasy RTT[11442]: Connection failed because:
Oct 01 01:25:37 greasy RTT[11442]: TransportOsError: (111) Connection refused
Oct 01 01:25:37 greasy RTT[11442]: Connection failed because:
Oct 01 01:25:37 greasy RTT[11442]: TransportOsError: (111) Connection refused

**Comment by radkesvat** [comment]
خیر اینو تست کردم اصلا این حالتی که میگید ممکن نیست ؛ باید با ایپی وی ۶ به ایپی وی ۶ ایران وصل شه طور دیگه نمیشه

**Comment by radkesvat** [comment]
در سرور ایران با این دستور میتونید ایپی وی سیکس سرورتون رو ببینین

> sudo ifconfig

اون خطی که نوشته <global>

**Comment by Hamed-F** [comment]
> خیر اینو تست کردم اصلا این حالتی که میگید ممکن نیست ؛ باید با ایپی وی ۶ به ایپی وی ۶ ایران وصل شه طور دیگه نمیشه

خب منظور منم همینه میگم این الان سرور خارج من داره سعی میکنه با ipv4 به ipv6 ایران متصل بشه که تو خط ارور  نشون میده خط اول

**Comment by radkesvat** [comment]
من اتصال با ایپی سیکس رو کامل تست کردم ولی فردا بازم تست میکنم و مشکلی باشه حتما رفع میشه ؛ شما هم اگه موفق نشدین وصل بشین لاگ و اطلاعات را قرار بدین چک میشه

**Comment by radkesvat** [comment]
> > خیر اینو تست کردم اصلا این حالتی که میگید ممکن نیست ؛ باید با ایپی وی ۶ به ایپی وی ۶ ایران وصل شه طور دیگه نمیشه
> 
> خب منظور منم همینه میگم این الان سرور خارج من داره سعی میکنه با ipv4 به ipv6 ایران متصل بشه که تو خط ارور نشون میده خط اول

خیر اون فقط لاگه منظور این نیست که گفتین

**Comment by Hamed-F** [comment]
> در سرور ایران با این دستور میتونید ایپی وی سیکس سرورتون رو ببینین
> 
> > sudo ifconfig
> 
> اون خطی که نوشته

من دوباره چک کردم اما ای پی درست بود

**Comment by oneoneishere** [comment]
آقا منم همین مشکل رو دارم
برای استفاده از آی‌پی ۶ نیاز هست مقدمات خاصی فراهم کنیم؟
از سرور خارج که پینگ میکنم آی پی ۶ سرور ایران  اوکی هست، ولی تانل همین خطایی که برای دوستمون نشون داده رو برا منم نشون میده

**Comment by radkesvat** [comment]
به rtt باید ایپی وی سیکس را بدون براکت بدین، براکتشو پاک کتیپ

**Comment by oneoneishere** [comment]
> به rtt باید ایپی وی سیکس را بدون براکت بدین، براکتشو پاک کتید

میدونم داداش راهنماتو خوندم دقیقا همونجوری انجام میدم ولی این مشکل همچنان هست
احساس میکنم شاید نیاز به تغییر خاصی هست توی سرور ایران یا خارج یه پیش نیازی تنظیمی چیزی

**Comment by radkesvat** [comment]
حتما امشب چک میکنم اینو ولی بعیده کار نکنه ؛ باید یه سرور ایران ایپی وی سیکس جدید پیدا کنم قبلیه به دیدار باقی شتافت متاسافنه

**Comment by radkesvat** [comment]
آقا من اینو تست کردم با ورژن 5.2

بدون مشکل با حداکثر سرعت وصل شد هم با ایپی وی ۴ چک کردم همه چیو هم وی ۶

فکر کنم ایپی وی سیکس سرور ایرانتونو اشتباه میزارد ؛ برای پیدا کردن ایپی وی سیکس روی سرور ایران این دستورو بنزید ؛ این خط که توش
global 
نوشته و توی عکس هم  با رنگ زرد زیرش خط کشیدم میشه ایپی وی سیکس ایرانتون

اگه این خط رو ندارید که توش global نوشته باشه یعنی سروتون ایپی وی سیکس نداره

> ifconfig

![image](https://github.com/radkesvat/ReverseTlsTunnel/assets/134321679/eb6c460b-0328-4d0a-bc4d-c476f7d5614a)

**Comment by oneoneishere** [comment]
نه داداش مشکل من اون نبود، من دردشو پیدا کردم
مشکل وقتی پیش میاد که با آی‌پی ۶ مالتی پورت اجراش میکنی
من چون سرویس تنظیم کرده بودم به صورت مالتی پورت اجرا بشه تنها چیزی که که تغییر میدادم آدرس آی پی بود و اصولا که بایستی با اون کار میکرد ولی نکرد
بعد دستی به صورت تک پورت اجرا کردم اوکی بود
حالا نمیدونم این موضوع قابل حل هست یا نه ولی خب هرچی هست این دو باهم کار نمیکنن

**Comment by oneoneishere** [comment]
ایول
ایکاش شرکتهای ایرانی که به صورت مستقیم بابت خدماتشون پول میگیرن هم همینقدر پشتیبانی و پیگیری داشتند 👍

**Comment by oneoneishere** [comment]
داداش من از دیشب تا الان روی سرورم با آی‌پی ۶ تست زدم، پنلم سنایی هست، امروز عصر به بعد که اوج مصرف شروع شد سرعت خیلی افت داشت پینگ بالا رفته بود، وقتی اینستا رو باز میکردم برای پخش یه کلیپ مدام وقفه ایجاد میشد
برگشتم روی آی‌پی ۴ بهتر شد اوضاع
گفتم فیدبک بدم بدونی، خواستی خودت یه بررسی بکن.

**Comment by radkesvat** [comment]
خوب اگه تونستین یه بار تونلو با همون ایپی وی ۶ فقط ری استارت میکردین... ببینیم تغییری ایجاد میکرد یا نه چون اگه تغییری ایجاد نکنه به شبکه دیتا سنتر مربوط میشه

**Comment by Hamed-F** [comment]
خب باتوجه به اینکه مشکل ipv6 حل شده این issue رو میبندم
تشکر 🌺
