### ISSUE TITLE
پیشنهاد در مورد مصرف رم و cpu

### ISSUE THREAD

**Issue by AkramiPro** [radkesvat/ReverseTlsTunnel#149]
درود خسته نباشید
یه مدت هست که داک haproxy رو دارم مطالعه میکنم و چیز های خیلی خوبی در مورد اینکه چطوری داره ترافیک رو مدیریت میکنه نوشته
طبیعی هست که داره از یک سیستم queue  برای مدیریت و پاسخ به درخواست ها استفاده میکنه
ولی فرض کنید من داخل مرورگر یه ادرس رو میزنم که باز بشه . درخواست میره داخل queue ولی من از داخل مرورگر تب رو close میکنم 
اینجا با اینکه من تب رو بستم ولی درخواست هم چنان داخل queue  هست و حذف نمیشه 
و جالب تر اینکه حتی درخواست از داخل queue  اجرا میشه ولی موقعی که بخواد response رو ارسال کنه متوجه میشه که کاربر abort کرده و اونجا خطا میخوره 
نکته منفی این داستان این هست که queue وقتی کاربر زیاد باشه ممکن هست بیخودی پر بشه از درخواست هایی که abort شدن و لازم نیست اصلا اجرا بشن
حالا اینجا میشه این رو مدیریت کرد و به haproxy گفت اگر کاربر abort کرده بود از توی queue  هم حذف کنه و انجام نده 
اینطوری مقدار زیادی توی مصرف منابع طبق گفته خودش صرفه جویی میشه
ممکن هست مشکلاتی هم ایجاد کنه که از علم من خارج هست
صرفا خواستم پیشنهاد بدم که بررسی کنید اگر میشه همچین چیزی روی RTT هم پیاده سازی بشه
شاید بتونه توی مصرف منابع کمک کنه

توضیحات بیشتر و منبع :

https://docs.haproxy.org/2.8/configuration.html#4-option%20abortonclose

چند تا مورد دیگه هم هست مثل keep-alive و tcp-fast-open که نمیدونم اینا رو در RTT پیاده سازی کردید یا خیر . اینا هم فکر کنم تاثیر مثبتی توی سرعت و stable بودن تانل داشته باشن 

من متاسفانه درک عمیقی از بحث شبکه و پروتکل ها ندارم  پیشاپیش از اینکه ممکن هست اشتباه گفته باشم عذرمیخوام

**Comment by radkesvat** [comment]
ممنون که گفتین البته بیشترون رعایت شده همین الان هم ، ولی سعی میکنم بهینه تر کنم اگه جا داشته باشه

**Comment by AkramiPro** [comment]
تشکر
