### ISSUE TITLE
نصب نشدن کامل RTT و اجرا نشدن تونل multiport

### ISSUE THREAD

**Issue by matinahm** [radkesvat/ReverseTlsTunnel#156]
بعد از نصب کامل با اسکریپت به این مشکل خوردم که تانل ران نمیشه 
وقتی RTT رو کامپایل کردم در اخر این ارور هارو داد
fatal error: string.h: No such file or directory
   28 | #include <string.h>
   
   Error: unhandled exception: FAILED: nim build_server [OSError]

**Comment by radkesvat** [comment]
سلام شما نباید کامپایل کنید ؛ از نصب مالتی پورت استفاده کنید ؛ کامپایل برای تست و تغییرات برنامه نویسی هست یا سیستم عامل هایی که RTT براشون خروجی گرفته نشده

**Comment by matinahm** [comment]
بله اول نصبو انجام دادم و به مشکل میخوره و میگه Tunnel service failed to start

**Comment by matinahm** [comment]
اینم وقتی با روش دوم نصب شد:
● tunnel.service - Reverse TLS Tunnel
     Loaded: loaded (/etc/systemd/system/tunnel.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-10-03 22:48:38 UTC; 7s ago
   Main PID: 10737 (code=exited, status=203/EXEC)
        CPU: 769us

**Comment by radkesvat** [comment]
این دستورو بزنید و نتیجه رو بفرستید 
در حد یه صفحه انتهای دستور

> journalctl -u tunnel.service -e -f

**Comment by matinahm** [comment]
تو ورژن جدید با اسکریپت مشکل حل شد ممنون
