### ISSUE TITLE
multi port with ufw enabled

### ISSUE THREAD

**Issue by ahmad-79** [radkesvat/ReverseTlsTunnel#16]
درود
مهندس سرور ایران هر دو پورت 80 و 443ش باز هستش تو تنظیمات ufw ولی وقتی با دستور زیر تونل رو روی سرور ایران ران میکنم ترافیکی جابجا نمیشه

`./RTT --iran --lport:443-443 --add-port:80 --sni:splus.ir --password:132 --keep-ufw`

ولی اگر --keep-ufw رو بردارم تونل بدون مشکل کار میکنه
لازمه پورت دیگه‌ای هم allow کنم؟

راستی اگر دستور رو به شکل زیر اجرا کنم خطا میگیرم و ازم میخواد lport بدم بهش
`./RTT --iran --lport:443 --add-port:80 --sni:splus.ir --password:132 --keep-ufw`

**Comment by radkesvat** [comment]
درسته مورد دوم یه خطای برسی ارگومان ها بود تو این نسخه رفع شده ؛ برای اینکه خودتون تو نسخه قبل درستش کنید اینطوری بهش بدین فعلا
--lport:443-443
تا متوجه مالتی پورت بودن بشه
بعد اینکه باید اون ufw disable فقط جولوی اجرا شدن این کامند رو میگرفت
> sudo ufw disable
کار خاص دیگه ای انجام نمیداد تا جایی که میدونم ولی چک میکنم ببینم اگه کار دیگه ای هم میکرد خارج از شرطش کنم

**Comment by ahmad-79** [comment]
خودم ufw رو غیرفعال کنم بعدش با --keep-ufw هم جواب میده دستور
شاید مشکل از کانفیگ فایروال باشه

فقط مسئله اینه که هر دو پورت 80 و 443 بازن و در اصل سرور خارج باید فقط همون پورت 443 رو کانکت شه تا جای که میدونم
و منم سوالم اینه که رو حالت مولتی پورت سرور خارج به جز iran-port:443 از پورت دیگه‌ای هم استفاده میکنه من رو فایروال سرور ایران allow کنمش؟

ممنون میشم اگر امکانش هست ببینید میشه reprodceش کرد یا نه؟

./RTT --iran --lport:443-443 --add-port:80 --sni:splus.ir --password:321 --keep-ufw
./RTT --kharej --iran-ip:91.19.91.19 --iran-port:443 --toip:127.0.0.1 --toport:multiport --password:321 --sni:splus.ir --keep-ufw

ufw status:
Default: deny (incoming), allow (outgoing), disabled (routed)
22/tcp                     LIMIT IN    Anywhere
443/tcp                    ALLOW IN    Anywhere
80/tcp                     ALLOW IN    Anywhere

**Comment by radkesvat** [comment]
سرور خارج وصل میشه به پورت ایران (۴۴۳) و در حالت مالتی پورت هم بازم همین اتقاف میفته و همچنین سرور خارج هیچ پورتی خاصی رو listen نمیکنه ؛ من الان واقعیتش یکمی سرم شلوغه و درگیر یه اموزش هستم  باز یکمی task ها انجام بشه میام سراغ این موارد

یه نکته ای هم دقت کنید ؛ بعضی از دوستان تصور میکنن اگه ufw خاموش باشه پورت های سیستمشون باز میشه که این تصور اشتباهه و سیستم عامل همه پورت هارو میبنده به جز اونایی که برنامه ها درخواست کنن باز کنن ؛ برای دیدن این پورت ها هم 
> netstat -tunlp 

من روی سیستم خودمم ufw استفاده نمیکنم خلاصه ؛ ولی این مورد برسی میشه

**Comment by radkesvat** [comment]
این نسخه رو یه برسی مجدد باید بکنم موقتا ریموش کردم تا شب که این مشکلاتش رفع بشه

**Comment by ahmad-79** [comment]
درود
نسخه 3.3 رو از همون موقع رلیز روی چندتا سرور ران کردم و رم کاملا پایدار شده و دیگه اسپایکی تو نمودار استفاده در کار نیست 👍
به طرز تعجب‌آوری هم بهینه‌ست و زیر صد مگ رم اشغال کرده سمت ایران
خود تونل هم هیچ قطعی و افتی نداشته
مشکل ufw هم به کل حل شده و من که پورت 80 و 443 رو تانل کردم فقط همونا رو allow دارم
حتی محض تست outgoing رو هم محدود به 443 و 80 کردم بازم تونل برقرار شد پس دیگه از پورت پرت و رندومی استفاده نمیشه
انشالا mux رو هم همین امروز تست میگیرم ببینم اوضاع اون چطوره😁
بدون mux که الان عالیه تونل
خلاصه که دست مریزاد♥

فقط ی سوالی برام پیش اومده قبل از بستن ایشو ازتون میپرسم با اجازه
مهندس امکانش هست لود بلنسینگ رو روی یک سرور با چندتا آیپی پیاده کرد؟
یعنی مثلا سرور هتزنر هم از آیپی اصلیش استفاده کنه و هم از floating ip که تشخیص تونل خیلی سخت‌تر شه و در صورت از دست رفتن ی آیپی باز هم تونل وصل بمونه؟

راستی ی سوال دیگه: pool رو کم کنیم افت کارایی نداره تونل؟

**Comment by radkesvat** [comment]
ماکس کدش کامنت شده باید نسخه بعد فعالش کنم که چیز مهمی نیست چون لود بالانس هست و بدون ماکس هم من دیگه مطمعن شدم نمیتونن تشخیص بدن الان چند روزه رو یه ایپی استفاده کردم مشکلی پیش نیومده ولی توی برنامه دارمش که وقت کنم فعال و تستش میکنم

در مورد سوال دوم ... واقعیتش دقیق نمیدونم این چطوری باید انتخاب بشه ... شاید یه اسکریپتی به سیستم عامل باید بگه چه ایپی ایی استفاده بشه برای اوت بوند کانکشن ها شایدم توی کد بشه انتخاب کرد اینترفیس رو دقیق نمیدونم این رو باید سرچ کنیم شاید نیازی به تغییر در کد نباشه ...
