### ISSUE TITLE
نکته در مورد udp

### ISSUE THREAD

**Issue by AkramiPro** [radkesvat/ReverseTlsTunnel#169]
درود خسته نباشی مهندس 
چند وقت پیش گفتید دیگه میرید روی udp  و ipv6 کارکنید که ipv6 رو اوکی کردید ممنون فقط udp مونده
دیدم یوسف جان برای bepass ظاهراً یه پراکسی نوشته که همه حالت های مختلف رو ساپورت می‌کنه 
گفته شاید بتونید از اون کدی که زدن استفاده کنید توی این پروژه و دیگه چرخ رو از اول طراحی نکنید 
https://twitter.com/uo0sef/status/1711336632194879650?s=19

بازم تشکر

**Comment by radkesvat** [comment]
بله دیدم ؛ کار خیلی خوبی کرده ولی برای این پروژه کاربرد نداره برای هسته ها کاربردیه
