### ISSUE TITLE
Error: Target server was not a trusted tunnel client, closing

### ISSUE THREAD

**Issue by mhmkt** [radkesvat/ReverseTlsTunnel#17]
سلام و تشکر بابت زحمتاتتون
توی سرور خارج این خطا را میگیرم و اتصال بر قرار نمیشه؟

connecting to *.*.*.*:443 (sni: aparat.com) ...
connecting to *.*.*.*:443 (sni: aparat.com) ...
[SslConnect] conencted !
[SslConnect] conencted !
[createNewCon] registered a new connection to the pool
[createNewCon] registered a new connection to the pool
[proccessClient] Target server was not a trusted tunnel client, closing...
[proccessClient] Target server was not a trusted tunnel client, closing...

**Comment by mhmkt** [comment]
سرور ایران اوبونتو 20 و سرور خارج اوبونتو 22 هست.

با عوض کردن SNI هم مشکل حل نشد

**Comment by radkesvat** [comment]
این خطا میتونه به این معنی باشه که فایروال جولوی اتصال سرور خارج شما رو گرفته با یه ایپی دیگه خارج تست کنید ببینید مشکل رفع میشه یا نه ؛ اگه نشد برام بفرستید دستوراتی که اجرا میکنید را

**Comment by mhmkt** [comment]
من یک سرور جدید اوبونتو ۲۰ ساختم و فقط پنل سنایی نصب کردم و برنامه را دانلود و نصب کردم و با این دستور اجرا کردم باز هم همون خطا را داد:
`./RTT --kharej --iran-ip:*.*.*.*.138 --iran-port:443 --toip:127.0.0.1 --toport:443 --password:*** --sni:aparat.com`

**Comment by miladtavakoli** [comment]
با این دوتا sni هم مشکل برطرف نشد.
داخل لاگ سرور ایران هم آیپی سرور خارج هم پرینت میشه ولی سرور خارج همون خطا رو میده. 
[proccessClient] Target server was not a trusted tunnel client, closing...

از سرور خارجم ssh , ping دارم و حتی از FakeTlsTunnel  که خودتون زحمتش رو کشیدین استفاده میکنم و بدون مشکل کار میکنه. ولی این کار نمیده.

**Comment by mhmkt** [comment]
> اول اینکه این ۲ تا Sni رو تست کنید divar.ir , splus.ir
> 
> اگه بازم همین خطا رو گرفتید یعنی ایپی خارجتون بلاک شده نمیتونه به ایران وصل بشه کلا یا اینکه password توی دستور داخل و خارج مغایرت داره چک کنید کاراکتر نا متعارفی اون وسط نباشه که تغییر داده باشه پسورد رو

با تغییر sni تفاوتی نداشت و همچنان خطا داد
پسوورد را هم 123 و تاثیری نداشت
یه کانفیگ دایرکت بدون tls هم ساختم و سایهای ایرانی را باز کرد
از سرور هم پینگ گرفتم به سایتای ایرانی پینگ داد

**Comment by miladtavakoli** [comment]
من مشکلم رو متوجه شدم!
اختلاف ورژن RTT داشتم بین سرور ایران و سرور خارج. 👍🏼

**Comment by mhmkt** [comment]
> من مشکلم رو متوجه شدم! اختلاف ورژن RTT داشتم بین سرور ایران و سرور خارج. 👍🏼

سپاس
مشکل منم همین بود

**Comment by radkesvat** [comment]
اها 😅 عجیبه این به ذهنم نرسیده بود

**Comment by retina20** [comment]
وقت بخیر.
این ارور:
[proccessClient] Target server was not a trusted tunnel client, closing...
در نسخه جدید ( برگشت به نسخه 2 ) دوباره به وجود آمده. در صورتی که در ورژن (2.1) اتصال برقرار میشد.
موارد زیر بررسی شده ولی مشکل حل نشده است:
1- تغییر sni
2- پاک کردن اسکریپت و نصب دوباره
3- بررسی پسورد و sni یکسان در هر دو سرور

**Comment by radkesvat** [comment]
@retina20

شما فکر کنم همون لحظه که منتشر کردم نسخه ۳ رو نصب کردین ؛ پیشناهاد میکنم یه بار دیگه دستور نصبو اجرا کنید تا همون نسخه ۳ نصب شه چون یه تغییر خیلی کوچیک هست که بهتره داشته باشین stable تره

**Comment by miladtavakoli** [comment]
خب سلام دوباره
 بعداز آپدیت به ورژن ۳.۳ دوباره این خطا رو گرفتم 
این بار بعد از خطا برای اینکه مطئن بشم ورژن ها یکی باشن scp کردم یه فایل رو روی سرور ایران و خارج.
برگشتم به همون ورژن ۲ الان داره درست کار میکنه.

سرور ایران:
5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

سرور خارج:

5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

**Comment by miladtavakoli** [comment]
@retina20 
ممنون،
ولی با غیرفعال کردن وارپ هم نتیجه تغییری نکرد.
نسخه ۳.۵ هم تست کردم ولی مشکل داشت
ولی برمیگردم نسخه ۲ بدون مشکل کار میکنه

**Comment by radkesvat** [comment]
مطمعنید نسخه اخر مشکل داشت؟ هم ایران و هم خارج اپدیت و تست کردین،  مشکلش رو میتونید توضیح بدین؟

**Comment by miladtavakoli** [comment]
مهندس جان اوکی شد با ورژن ۳.۵
نمیدونم مشکلش از کجا بود
فقط دفعه اخر ریبوت کردم سیستم و بعد تست کردم اوکی شد
ممنون ازتون
