### ISSUE TITLE
Could not resolve host

### ISSUE THREAD

**Issue by NgmNjt** [radkesvat/ReverseTlsTunnel#177]
سلام من رو سرور ایرانی که میخوام روش اولو اجرا کنم این ارور رو میده 
curl: (6) Could not resolve host: raw.githubusercontent.com

**Comment by NgmNjt** [comment]
در رابطه با tls handshake timeout روی اپراتور همراه اول هم اطلاع دارید؟

**Comment by AkramiPro** [comment]
به احتمال زیاد با عوض کردن sni مشکل حل بشه . 
myket.ir
این تست کن

**Comment by NgmNjt** [comment]
نه نمیشه من با TCP میزنم تو هدرش زدم نشد دوباره
ممکنه مشکل از تانل باشه؟ ایپی تیبل زدم رو ابر اروان

**Comment by radkesvat** [comment]
درمورد ایپی تیبل نظری ندارم ... هر جایی جواب نمیده ؛ با تونل RTT مشکل هند شیک دارید روی همراه ؟

**Comment by NgmNjt** [comment]
نه با تانل ip table مشکل tls handshake timeout روی همراه اول رو دارم 
و وقتی خواستی تانل rtt رو بزنم رو سرور ایران که ابر اروان باشه curl: (6) Could not resolve host: raw.githubusercontent.com این ارور رو داد (نکته قابل توجه اینه که یهو رو همراه اول کار نمیکنه دوباره 8-7 ساعت بعدش مثل قبل وصل میشه و کار میکنه باز دوباره قطع میشه)

**Comment by radkesvat** [comment]
روی سرور ایرانتون این دستورور اجرا کنید بعد rtt رو دوباره امتحان کنید

> echo nameserver 8.8.8.8 | sudo tee /etc/resolv.conf
