### ISSUE TITLE
مشکل سرتیفیکیت نشدن

### ISSUE THREAD

**Issue by NgmNjt** [radkesvat/ReverseTlsTunnel#181]
Hint: The Certificate Authority failed to download the challenge files from the                                                                                                       temporary standalone webserver started by Certbot on port 80. Ensure that the li                                                                                                      sted domains point to this machine and that it can accept inbound connections fr                                                                                                      om the internet.

Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See t                                                                                                      he logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for mo                                                                                                      re details.
سلام من میخوام که ساب دامنه رو تغییر بدم و سرتیفیکیت جدید بگیرم اما هر دفعه همین ارور ظاهر میشه

**Comment by masih1998** [comment]
سلام یک برنامه ای داره از پورت 80 سرور شما استفاده میکنه که Certbot نمیتونه سرتیفیکیت بگیره
با دستور 
`netstat -tulpn | grep LISTEN | grep :80`
میتونید بفهمین چه برنامه ای هستش که موقت ببنیدینش سرتفیکیت رو بگیرین دوباره اجراش کنین

**Comment by NgmNjt** [comment]
ممنون
شما راجب ارور tls handshake timeout هم اطلاع دارید؟
