### ISSUE TITLE
مشکل در واتساپ با اینترنت ایرانسل

### ISSUE THREAD

**Issue by Asfia7** [radkesvat/ReverseTlsTunnel#192]
سلام مهندس خسته نباشید 
من با reverse tls tunnel با اینترنت همراه اول با واتساپ مشکلی ندارم و همه چی اوکیه

ولی با بقیه اپراتور های اینترنت داخل واتساپ چیزی دانلود یا اپلود نمیشه

مشکل از چیه؟!

**Comment by radkesvat** [comment]
مشکل از سرور ایرانه به نظرم ؛ نمیشه تونل رفتار متفاوتی نشون بده برای کلاینت ها

**Comment by Asfia7** [comment]
امکان داره که از سرور خارج باشه؟
چون سرور ایران رو عوض کردم فرقی نکرد

**Comment by radkesvat** [comment]
اگه از سرور خارج باشه هیچ کس نباید بتونه با واتساپ دانلود کنه ؛ به نظرم چند تا کانفیگ مختلف بخصوص وب سوکت بسازید و تست کنید در گوشی کاربرا

**Comment by Asfia7** [comment]
با وب سوکت زدم درست شد

ممنون مهندس

**Comment by radkesvat** [comment]
خواهش ؛ با توجه به حل شدن مشکل من ایشیو رو میبندم
