### ISSUE TITLE
میزان مصرف ترافیک

### ISSUE THREAD

**Issue by majiix** [radkesvat/ReverseTlsTunnel#198]
سلام. مرسی از زحماتتون. میخواستم بدونم دلیل اینکه مقدار مصرف ترافیک در سرور ایران بیشتر از سرور خارج هست چیه؟ چرا یکسان نیستن این دو مقدار؟ و به نظر میرسه ترافیک در سرور ایران خیلی بیشتر مصرف میشه تا خارج.

**Comment by majiix** [comment]
یکی از سرورها رو چک میکردم تو 19 روز گذشته 1.15 ترا مصرف داشته روی سرور خارج در صورتی که در سرور ایران حدود 2.5 ترا مصرف شده. چرا اینطوریه؟

**Comment by majiix** [comment]
از آپلود فیک و noise  هم استفاده نمیکنم من.

**Comment by radkesvat** [comment]
آروان ترافیک اپلود بعلاوه دانلود شمارو نشون میده و در فاکتور لحاظ میکنه

یعنی کاربر یک گیگ با وی پی ان دانلود کنه سرور ایران شما ۱ گیگ دانلود و ۱ گیگ اپلود کرده و در نتیجه ۲ گیگ ترافیک مصرف کرده

بعضی دیتا سنتر ها اپلود رو هزینه نمیگیرن ولی اروان اینطوری نیست.

**Comment by majiix** [comment]
گزینه‌ی پیشنهادی به جای آروان دارید لطفا؟ که مسخره بازیشون کم باشه.

**Comment by radkesvat** [comment]
والا هستن جاهای دیگه ولی چون من خودم رو اروان هستم از کیفیت بغیه جاها اطلاعات دقیق ندارم ؛ ولی در کل پیشناهاد میکنم لایزر ؛ ویراک کلود و میزبان داده رو تست کنید این ها قیمت های  به صرفه تری نیز دارند
