### ISSUE TITLE
محل نصب پنل

### ISSUE THREAD

**Issue by yaserchali** [radkesvat/ReverseTlsTunnel#2]
سلام وقتتون بخیر باشه 
وخسته نباشید میگم بابت تمام زحماتی که میکشید خداخیرت بده
یه سوال داشتم میشه توی حالت ریورس پنل x-ui رو روی سرور ایران نصب کنیم؟
یا حتما باید روی خارج نصب بشه؟
یا هردوحالت میشه؟
ممنون میشم در این باره بهم یه راهنمایی کووچیکی بکنید خیلی ممنون تشکر

**Comment by radkesvat** [comment]
من فرض کردم پنل روی سرور خارج نصب هست ؛ روی سرور ایران اگه باشه باید روش ها پنل به پنل رو انجام بدین و این برنامه میشه گفت بلا استفاده میشه

**Comment by yaserchali** [comment]
خیلی ممنون تشکر خیلی هم عالی

**Comment by yaserchali** [comment]
من‌همین الان تستش کردم خیلی عالی کار کرد
دوست دارم روی ایپی کثیف هم تستش کنم ببینم بازم کار میکنه یانه
خلاصه خواستم تشکر کنم

**Comment by radkesvat** [comment]
خواهش میکنم ؛ ممنون که تست کردید و نتیجه را اطلاع دادین

**Comment by yaserchali** [comment]
قوربون شما
من این خبر پابلیک شدن این تانل رو توی گروه رسمی تلگرامی پنل ثنایی گفتم 
هم پیام منو پاک کردن هم منو ۱۰ روز به جرم تبلیغ کردن از چت محروم کردن نمیفهمم چرا واقعا😂😂

**Comment by radkesvat** [comment]
شاید ربات تشخیص لینک اینکارو کرده ؛ بعضی گروها دیدم حتی شب ها محدودیتشو زیاد میکنن ؛ درکل ممنون ؛ الان خیلی از روش ها کار میکنن و من خودم به این فرض که فیلترینگ قرار شدید بشه اینو منتشر کردم ؛ که امیدوارم نشه 

اگرم ایپی تمیز دارید و دنبال سرعت بیشتر هستید تونل های udp رو تست کنید ؛ ولی احتمال فیلتر شدنش هست

**Comment by yaserchali** [comment]
بله درسته الانی که دیدم روبات بودش
خیلی خوب کاری کردین منتشر کردین
متاسفانه من تاجایی که میدونم پروتوکل udp به خارج کلا بستس ولی ممنون بابت پیشنهادتون میرم دنبالشو میگیرم

**Comment by yaserchali** [comment]
درود 
من روی ایپی کثیف هتزنر تستش کردم
ایپی درحدی کثیف بود که پینگ نمیداد هم ایرانسل هم همراه اول 
ولی همین الان باهمون ایپی کثیف من دارم اینجا براتون کامنت میزارم😎😎
دست مریزاد👏👏👏
