### ISSUE TITLE
سرعت در آپلود فیک

### ISSUE THREAD

**Issue by majiix** [radkesvat/ReverseTlsTunnel#201]
سلام. میخوام بدونم آپلود فیک کلا باعث افت سرعت میشه یا هر چقدر اون عددِ نسبت (مثلا 9) بالاتر میره باعث کمتر شدن سرعت میشه؟

**Comment by radkesvat** [comment]
در نسخه اخر تلاش شده مشکلی برای سرعت ایجاد نکنه تا جایی که ممکن باشه ؛‌در کل تست و نتیجه گیری رو باید با ستاپ خودتون انجام بدین
