### ISSUE TITLE
راه اندازی سرویس در ویندوز سرور

### ISSUE THREAD

**Issue by MAMSEIN** [radkesvat/ReverseTlsTunnel#207]
با سلام و خسته نباشید.
ممنون بابت زحماتی که میکشید.
لطفا یک آموزش هم قرار دهید برای کسانی که از ویندوز سرور استفاده میکنند.
من ویندوز سرور 2016 دارم. چطور میتونم از این سرویس استفاده کنم و تونل بزنم؟ البته سرور خارج من لینوکس هست. فقط سرور داخل ایران من ویندوز سرور هست.
خیلی ممنون

**Comment by radkesvat** [comment]
سلام من خودم از ویندوز  سرور استفاده میکنم چون یه جا پورت ۱۰ گیگ بهم دادن ؛ به راحتی اجرا میشه کامند هاش مثل لینوکس هستند فقط در فایروال باید اجازه اینبودش رو به این صورت بدین ؛ یا کلا فایروال ویندوزو خاموش کنید که پیشناهاد نمیشه
فقط پورت ۴۴۳ کافیه ولی من چند تا پورت دیگه هم گزاشتم
![image](https://github.com/radkesvat/ReverseTlsTunnel/assets/134321679/9ba9e90f-ba9e-40a7-96b2-552cb2b3509b)

**Comment by radkesvat** [comment]
مقادیر سمت راستش همه ANY هستند

**Comment by MAMSEIN** [comment]
خیلی ممنون لطف کردید 👍
فقط یک سوال دیگه امکان Multiport توی ویندوز مقدور نیست درسته؟ چجوری به صورت سرویس چند پورت جداگانه رو ران کرد که اگر سرور ری استارت شد اونا دوباره ران شن؟
تشکر 

> سلام من خودم از ویندوز سرور استفاده میکنم چون یه جا پورت ۱۰ گیگ بهم دادن ؛ به راحتی اجرا میشه کامند هاش مثل لینوکس هستند فقط در فایروال باید اجازه اینبودش رو به این صورت بدین ؛ یا کلا فایروال ویندوزو خاموش کنید که پیشناهاد نمیشه فقط پورت ۴۴۳ کافیه ولی من چند تا پورت دیگه هم گزاشتم ![image](https://user-images.githubusercontent.com/134321679/277381068-9ba9e90f-ba9e-40a7-96b2-552cb2b3509b.png)

**Comment by radkesvat** [comment]
باید دو تا cmd باز کنید و برای هر پورت یه بار اجرا کنید ؛ برای اینکه بعد ری استارت اجرا بشن این داکیومنت کمکتون میکنه

https://www.windowscentral.com/how-create-and-run-batch-file-windows-10

**Comment by MAMSEIN** [comment]
لطف کردید. ممنون
