### ISSUE TITLE
مشکل در مولتی پورت با پروتکل UDP

### ISSUE THREAD

**Issue by MAMSEIN** [radkesvat/ReverseTlsTunnel#216]
سلام و خسته نباشید
من دیدم 2 هفته پیش یک نفر دیگه این موضوع رو بیان کرده بود اما آپدیت نشد و مشکل رفع نشده.
چه در سرور داخل چه خارج، من با چندین سیستم عامل های مختلف لینوکس و از شرکت های مختلف تست رو انجام دادم اما هیچکدوم کار نکردن و ارور داد.
تمام پکیج های iptables هم نصب است.
من کد دستوری زیر رو وارد میکنم:
root@localhost:~# ./RTT --iran  --lport:23-65535  --sni:mci.ir --password:021123 --accept-udp

و این پیام نشان داده میشه. حتی اگر فقط دو پورت مختلف رو باهم معرفی کنم و به این شکل رنج ندم بهش باز همین ارور رو میده.
version="6.7"
mode="iran"
listen_port=0
final_target_domain="mci.ir"
password="021123"
accept_udp=true
host=Hostent(name: "mci.ir", aliases: @[], addrtype: "AF_INET", length: 4, addrList: @["5.106.4.1"])

password="021123" password_hash="68738182BF25ADB08220D7EA805C95B9F5CDB70D" sh1=3866679936 sh2=2364622112 sh3=1877805780 download_cons=8 upload_cons=8 connection_age=30

fs.file-max = 1000000
Firewall stopped and disabled on system startup
Mode Iran (Tcp + Udp): *********  handshake: mci.ir
reseting iptable nat
fatal.nim(53)            sysFatal
asyncfutures2.nim(426)   futureContinue
asyncfutures2.nim(426)   futureContinue
Error: unhandled exception: globals.nim(131, 9) `0 ==
    execCmdEx(&"""iptables -t nat -A PREROUTING -p {FWProtocol} --dport {multi_port_min}:{multi_port_max} -j REDIRECT --to-port {listen_port}""").exitCode`  [AssertionDefect]
reseting iptable nat
لطفا مشکل رو بررسی کنید و یک راه حل ارائه دهید.
باتشکر

**Comment by MAMSEIN** [comment]
من کلا با 4 تا پورت کار دارم. میتونم جداگانه 4 تا خط برای هرکدوم دستور بدم و به صورت سرویس اجرا کنم اما نمیدونم باعث میشه توی مصرف رم و سی پی یو تاثیر داشته باشه یا خیر.

**Comment by radkesvat** [comment]
احتمالا iptables نصب نیست روی اون سیستم

**Comment by dextercage** [comment]
منم این مشکل رو وقتی فلگ --accept-udp رو اضافه میکنم میگیرم. ۲ تا تانل ران کردم ولی قبل این فلگ این مشکل نبود. و در ضمن وقتی که یک تغییری میدم توی سرویس با daemon-reload و بعد سرویس رو استارت میکنم همین ارور رو میده و حتما باید سرور رو ریست بدم تا درست شه. احتمالا مشکل از رول های آی پی تیبله ولی دستورات زیر کمک نمیکنه و باید ریست بشه

iptables -t nat -F
iptables -t nat -X

ip6tables -t nat -F
ip6tables -t nat -X

**Comment by pedram222** [comment]
همچنان این مشکل است و همچنان هم مطمینم که iptables نصبه
