### ISSUE TITLE
قطعی تانل همزمان با وارپ

### ISSUE THREAD

**Issue by The-Binary-0-1** [radkesvat/ReverseTlsTunnel#225]
سلام ارادت
از پروژه ای که لینکش رو میذارم واسه وارپ پلاس روی سرور خارج استفاده مبکنم و یه مشکلی که هست و نمیدونم علتش چیه اینه که زمانی که وارپ رو به صورت گلوبال میکنم که کل سرور از وارپ رد بشه تانل قطع میشه ولی پنل هیدیفای و کانفیگ های ریلیتی که مستقیم هستن قطع نمیشن و اوکی هستن
هر دو سرور هم پینگ همدیگه رو دارن
داخل دستور سرور خارج to ip رو عوض کردم به جای 127 آی پی سرور رو زدم ولی بازم فرقی نکرد

https://gitlab.com/fscarmen/warp

**Comment by radkesvat** [comment]
ببینید بعد از اینکه ورپ رو انجام دادین و تونل رو ستاپ کردین ؛ یک بار تونل رو در سرور ایران ری استارت کنید تا ایپی جدید سرور خارج رو بشناسه ؛ البته نمیدونم ولی این شاید مشکل رو حل کنه

**Comment by The-Binary-0-1** [comment]
احسنت. مشکل همین بود و با ریستارت سرویس ایران حل شد... سپاس

**Comment by The-Binary-0-1** [comment]
سلام مجدد... مشکل حل شد ولی حل نشد!
یعنی با ریستارت تانل برقرار میشه ولی پایدار نیست و بعد از چند دقیقه شروع میشه قطع و وصل شدن.
سمت ایران این اررور
Nov 22 11:11:02 ubuntu RTT[143292]: [AssociatedCon][Error] left without connection, closes forcefully.
سمت خارج این اررور
Nov 22 14:43:14 ubuntu RTT[117203]: (X509BadServerName) Expected server name was not found in the chain (code: 56)
Nov 22 14:43:14 ubuntu RTT[117203]: (X509BadServerName) Expected server name was not found in the chain (code: 56)
Nov 22 14:43:16 ubuntu RTT[117203]: prallel upload: 8   parallel download: 9   outbounds: 2
Nov 22 14:43:21 ubuntu RTT[117203]: [Warn] few connections exist!, retry to connect in 3 seconds....

راهی نداره که سرویس رو bind کنیم به یه اینترفیس؟
به نظرم میاد بدلیل اینکه warp یه اینترفیس با آی پی 172.16.0.2 میسازه و ترافیک از اون عبور میکنه اگر امکانش باشه که سرویس رو اجبار کنیم که فقط از اینترفیسی که آی پی اصلی سرور روش هست استفاده کنه مشکل حل بشه. وارپ رو خاموش میکنم مشکل قطع و وصلی و اررور ها حل میشه... سپاس دوست عزیز.

**Comment by radkesvat** [comment]
میتونید از این استفاده کنید

https://github.com/JsBergbau/BindToInterface
