### ISSUE TITLE
مشکل اجرای روی centos 7

### ISSUE THREAD

**Issue by dextercage** [radkesvat/ReverseTlsTunnel#226]
متاسفانه نمیشه روی سنت او اس نسخه سی رو بالا برد و این ارور رو میده
/root/RTT: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /root/RTT)

سعی کردم روی داکر با ایمیج debian:stable-slim اجرا کنم ولی هیچ خروجی چاپ نمیکنه ولی وقتی میخوام روی خود هاست نصب کنم میگه:
Tunnel is running!. you must stop the tunnel before update. (pkill RTT)
update is canceled.
راه حل؟

**Comment by radkesvat** [comment]
باید برنامه رو کامپایل کنید اگه ارور Libc میگیرید
اسکریپتی که تو گیت هاب هست گزینه کامپایل داره ؛ اگرم میخواید دستی کامپایل کنید 
https://github.com/radkesvat/ReverseTlsTunnel/blob/master/docs/Compile.md

**Comment by dextercage** [comment]
> باید برنامه رو کامپایل کنید اگه ارور Libc میگیرید اسکریپتی که تو گیت هاب هست گزینه کامپایل داره ؛ اگرم میخواید دستی کامپایل کنید https://github.com/radkesvat/ReverseTlsTunnel/blob/master/docs/Compile.md

سلام ممنون چک میکنم.

حالا گزینه داکرایز شدن هم هنوز روی میزه. به نظر شما چرا این مشکل ایجاد شده؟
به داکرایز کردن پروژه فکر نمیکنید؟

**Comment by radkesvat** [comment]
داکر nat داخلی ایجاد میکنه و برنامه تو سرور ایران ایپی خارجو نمیتونه بخونه و مشکل ایجاد میکرد ؛ روی داکر قبلا تستش کردم

**Comment by dextercage** [comment]
خیلی هم عالی ممنون از پاسختون.
