### ISSUE TITLE
عدم کارکرد آپلود فیک

### ISSUE THREAD

**Issue by The-Binary-0-1** [radkesvat/ReverseTlsTunnel#229]
سلام و ارادت
دوست عزیز امروز متوجه شدم آپلود فیک انجام نمیشه و ترافیک یک به یک شده. پاک کردم دوباره نصب کردم/سوییچ accept udp رو پاک کردم ولی فرقی نکرد. علت چیه؟ قبلا مشکلی نداشت و کار میکرد.
روی سرور هم تغییر خاصی اعمال نشده نسبت به قبل.
سپاس

**Comment by The-Binary-0-1** [comment]
درود مجدد
آقا من کلی تست با مدلهای مختلف گرفتم. شرایط سرور ایران اینه که کاربرش فقط خودم هستم و ترافیکی روش نیست. وقتی که مثلا با دانلود منیجر شروع به دانلود میکنی اگر یکی دو بار دانلود استاپ و رزیوم بشه (یعنی پهنای باند بدون ترافیک بشه و دوباره ترافیکش بره بالا) قاطی میکنه و آپلود فیک رو انجام نمیده. بعضا پیش میاد که دانلود رو پاز میکنی و پهنای باند بدون ترافیک میشه یهو شروع میکنه به آپلود با پهنای باند بالا.
حالا شما بفرما به نظرتون چیه مشکل؟

**Comment by radkesvat** [comment]
اپلود فیک توازنش متغیر هست به این صورت که اگه شما ۱ گیگ دانلود کنی ۹ گیگ رو به صورت مستقیم اپلود نمیکنه ؛ بر اساس پهنای باندی که هست تلاش میکنه آرام آرام اپلود کنه ؛ در کل درون خودش حساب میکنه چند بایت باید اپلود فیک بکنه و آمارشو داره
