### ISSUE TITLE
تک کاربره کردن

### ISSUE THREAD

**Issue by masih1998** [radkesvat/ReverseTlsTunnel#232]
سلام مهندس وقت شما بخیر
ببخشید مزاحم وقت شما میشم
من رو ببخشید
یک موضوعی هست خیلی وقته میخوام باهاتون در میون بزارم
در روش تانل، آیپی همه کاربران از سمت سرور خارج همون آیپی سرور ایران دیده میشه بخاطر همین قابلیت تک کاربره کردن ( IP Limit-Fail2ban) کلا کار نمیکنه..
اما در اسکریپت شما چون تانل برعکس هستش یعنی تانل از سمت سرور خارج به ایران این قابلیت باید کار کنه درسته؟ اما اصلا برای من کار نمیکنه
میشه بگین مشکل از سمت سرور من هستش؟ یا اسکریپت شما هم مثل سایر روش ها از تک کاربره( IP Limit-Fail2ban) کرده پشتیبانی نمیکنه؟

**Comment by radkesvat** [comment]
تک کاربره میخواید باید پنلو بیارید رو سرور ایران ؛ تونل معکوس هم نمیتونه این مشکل رو حل نه ؛ تنها راهش اینه که پنل رو سرور ایران باشه یا اینکه تونل مثلثی استفاده کنید یا اینکه تونل هایی استفاده کنید که لایه ایپی رو داخل هدر حمل کنند که اونها معمولا تونل های بین روتر هتسند و کار تخصصی هست و متاسفانه سیستم فیلترینگ هم تونل مثلثی هم تونل روتر رو (می تواند) تشخیص دهد.

اگه عمری باقی بود و تونل fpt تموم شد ؛ با اون ولی میشه اینکارو کرد

**Comment by masih1998** [comment]
سپاسگذارم
 تونل ftp رو خودتون قراره زحمتش رو بکشین؟

**Comment by radkesvat** [comment]
بله

**Comment by masih1998** [comment]
سپاسگذارم
دستتون دردنکنه
