### ISSUE TITLE
دلیل احتمالی کارنکردن UDP برای عده ای

### ISSUE THREAD

**Issue by Gharib110** [radkesvat/ReverseTlsTunnel#234]
من کد شمارو خواندم و راجب کی وورد all  توی فایل globals برای iptables استفاده میکنید. من تغییر دادم به udp و tcp یعنی یه دونه اجرای خطوط 131 فایل به ازای udp و tcp دیگر اون ایرادی که دوستان گفتند  را نداد اما این ارور را داد
```bash
reseting iptable nat
Started tcp server  :::534
Started udp server  :::534
Connected client:  address=TransportAddress(family: "IPv6", address_v6: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 188, 121, 113, 103], port: 5678)
asyncfutures2.nim(586)   cb
Error: unhandled exception: Asynchronous task [handleDatagram() at iran_server.nim:509] finished with an exception "TransportOsError"!
Message: (107) Transport endpoint is not connected
Stack trace: common.nim(591)          raiseTransportOsError
```

کی وورد all برای تمام پروتکل هایی که در 
`` /etc/protocols ``
کار میکند اما 
--dport
مثلا بای udplite که نمیدونم چیه کارنمیکنه همون ارور --dport را که برای دوستان داد میدهد

**Comment by Gharib110** [comment]
این رو نگاه کنید خواهشا
https://serverfault.com/questions/563033/iptables-error-unknown-option-dport

**Comment by Gharib110** [comment]
template FWProtocol(): string = (if accept_udp: "all" else: "tcp")

#ip6tables -t nat -A PREROUTING -p tcp --dport 443:2083 -j REDIRECT --to-port
proc createIptablesForwardRules*() =
    if reset_iptable: resetIptables()
    if not (multi_port_min == 0.Port or multi_port_max == 0.Port):
        assert 0 == execCmdEx(&"""iptables -t nat -A PREROUTING -p {FWProtocol} --dport {multi_port_min}:{multi_port_max} -j REDIRECT --to-port {listen_port}""").exitCode
        assert 0 == execCmdEx(&"""ip6tables -t nat -A PREROUTING -p {FWProtocol} --dport {multi_port_min}:{multi_port_max} -j REDIRECT --to-port {listen_port}""").exitCode

    for port in multi_port_additions:
        assert 0 == execCmdEx(&"""iptables -t nat -A PREROUTING -p {FWProtocol} --dport {port} -j REDIRECT --to-port {listen_port}""").exitCode
        assert 0 == execCmdEx(&"""ip6tables -t nat -A PREROUTING -p {FWProtocol} --dport {port} -j REDIRECT --to-port {listen_port}""").exitCode

**Comment by Gharib110** [comment]
The error you're encountering is because the --dport option in iptables is specifically designed for TCP and UDP protocols. When you use the keyword all with -p, it includes all protocols, but not all protocols have the concept of ports.

**Comment by Gharib110** [comment]
`` cat /etc/protocols ``
فکر کنم باید ببینید چه پروتکل هایی رو نیاز داره این RTT به غیر از udp  و tcp برای انتقال اون تونل همه رو جدا جدا اد کنید

**Comment by Gharib110** [comment]
ببخشید این بخش از کدتون رو چک نکردین؟

**Comment by radkesvat** [comment]
سلام ایشیو رو کلوز کردین فکر کردم مشکل حل شده ؛ چک میکنم

**Comment by Gharib110** [comment]
بله تقصیر من بود آخه بعد اون اروری که گفتم چندبار دیگه ران کردم دیگه اون ارور رو در لحظه نمیداد تا اینکه وصل شدم یهو دوباره همون ارور که اول این issue گذاشتم raise شد و تونل بسته،شد
