### ISSUE TITLE
هندل کردن بهتر کانکشن ها

### ISSUE THREAD

**Issue by Mahdi-zarei** [radkesvat/ReverseTlsTunnel#25]
سلام و خدا قوت
امکان این هست برای سرور خارج یه لیمیت مشخص بزارید و در حالتی که کانکشن ها بلااستفاده هستن ازین تعداد بیشتر کانکشن باز نکنه؟ و همچنین با استفاده از keep alive و تاریخ آخرین receive کانکشن های فعلی رو پایش کنه و در صورتی که بیش از زمان مشخصی ( مثلا 5 دقیقه ) کانکشن بی استفاده بود و از لیمیت هم بیشتر کانکشن داشتیم بسته شه؟ چون حدس من این هست به علت تعدد زیاد کانکشن ها رم برنامه پر میشه.

**Comment by radkesvat** [comment]
سلام اینی که میکید در حتا حاضر هست هر کانکشنی ۶۰۰ ثانیه پکت رد نکنه بسته میشه

علت پر شدن رم چیز خیلی پیچیده ایه (مربوط به gc هست به نظرم)؟خودم چند وقته درگیرشم و امیدوارم بتونم رفعش کنم
