### ISSUE TITLE
قطع و وصل تلگرام بعد از آپدیت ورژن ۷

### ISSUE THREAD

**Issue by xSOH3ILx** [radkesvat/ReverseTlsTunnel#271]
سلام وقت بخیر
بعد از آپدیت به ورژن ۷، تلگرام رو کانکتینگ میمونه ، رو بقیه اپ‌ها و سایت‌ها مشکلی نیست( لگ هم ندیدم تو این چند دقیقه که استفاده کردم) ولی تلگرام خیلی سخت وصل میشه و قطع و وصل داره

مورد بعدی هم اسکریپت بعد از آپدیت ورژن رو هنوز ۶.۹ نشون میده

**Comment by m2tts2001** [comment]
دستورات داخل صفحه اصلی ورژن 6.9 رو نصب میکنه
من ورژن 7 رو بصورت دستی کامپایل کردم یکم دیگه نتیجه رو میگم

**Comment by SOH3IL-VD** [comment]
> دستورات داخل صفحه اصلی ورژن 6.9 رو نصب میکنه من ورژن 7 رو بصورت دستی کامپایل کردم یکم دیگه نتیجه رو میگم

خب با این فرمایش اصولا من باید بعد از آپدیت، هیچ تغییری تجربه نمیکردم موقع اتصال اگه روی همون ورژن 6.9 میموند. ولی به نظر میاد یکم با تلگرام به مشکل خوردم، هنوز مورد دیگه ای ندیدم و فقط همین تلگرامه

**Comment by navid4132** [comment]
> دستورات داخل صفحه اصلی ورژن 6.9 رو نصب میکنه من ورژن 7 رو بصورت دستی کامپایل کردم یکم دیگه نتیجه رو میگم


سلام
برای شما استیبل بود؟؟
چون برای من کانکشن ها استیبل نبودن

**Comment by sajadshadmn** [comment]
به جز مشکل در تلگرام مورد خاصی دیده نشد

**Comment by sajadshadmn** [comment]
برای من که مشکلی نداشت

**Comment by m2tts2001** [comment]
> > دستورات داخل صفحه اصلی ورژن 6.9 رو نصب میکنه من ورژن 7 رو بصورت دستی کامپایل کردم یکم دیگه نتیجه رو میگم
> 
> خب با این فرمایش اصولا من باید بعد از آپدیت، هیچ تغییری تجربه نمیکردم موقع اتصال اگه روی همون ورژن 6.9 میموند. ولی به نظر میاد یکم با تلگرام به مشکل خوردم، هنوز مورد دیگه ای ندیدم و فقط همین تلگرامه

من بازم تست کردم و ورزن 6.9 داره نصب میشه
اتفاقا من با ورژن 6.9 مشکل تلگرام داشتم و که به شدت کند بود

**Comment by m2tts2001** [comment]
تجربه من بعد از حدود 6 ساعت
فعلا همه چی خوبه اما بنظرم باید بیشتر بهش زمان داد

**Comment by xSOH3ILx** [comment]
> تجربه من بعد از حدود 6 ساعت
> فعلا همه چی خوبه اما بنظرم باید بیشتر بهش زمان داد

من یه مقدار مشکل دارم تو کانکشن، یعنی هنوز قطع و وصل وجود داره

نمیتونم تشخیص بدم که از اپراتوره یا از تانل یا چی

اپراتور: ایرانسل
سرور خارج : هتزنر
سرور ایران : فن‌آوا (شخصی)
پروتوکل: ریلیتی
