### ISSUE TITLE
تانل دو سرور خارج

### ISSUE THREAD

**Issue by sajadshadmn** [radkesvat/ReverseTlsTunnel#284]
درود استاد
به نظر شما اگر دو تا سرور خارج رو با ریورس به هم تانل کنیم 
سرور خارج اول که جای ایران کانفیگ میکنیم با توجه به اینکه در خواست از سرور خارج دوم شروع میشه چقدر میتونه از فیلتر شدن سرور خارج اول کمک کنه؟
با فرض بر اینکه کانفیگها رو هم وب سوکت بزنیم
با توجه به اینکه در این حالت چک ایپی فقط ایپی سرور خارج دوم رو نشان میده نه سرور خارج اول که دایرکت بهش وصلیم
ممنون

**Comment by sajadshadmn** [comment]
لطفا اگر اینکار تاثیری داره ممنون میشم نظر شما رو‌هم بدونم مهندس 
با تشکر

**Comment by ali4hk** [comment]
قبلا داشت الان نداره
