### ISSUE TITLE
اپلود فیک و  ترافیک  1/10

### ISSUE THREAD

**Issue by MahdiMadhani** [radkesvat/ReverseTlsTunnel#289]
با سلام
میخواهیم ی سرور ایران تهیه کنیم گفتن در صورتی که مصرف 1 به 10 باشه اوکیه.
ایا اپلود فیک رو فعال کنیم مصرف 1 به 10 رعایت میشه؟
با تشکر

**Comment by Arzenow** [comment]
سلام ارتباط به دیتا سنتر داره و دیتا سنترهای خوب اصولاً آپلود رو لحاظ می‌کنن
