### ISSUE TITLE
پیشنهاد، فرگمنت

### ISSUE THREAD

**Issue by MiladNoob** [radkesvat/ReverseTlsTunnel#326]
سلام مهندس جان دم شما گرم بابت زحماتت
امکان ترکیب تانل و فرگمنت هستش؟
اگه هستش به نظرت یه روزی یه جایی وقت میکنی اضافه کنی به پروژه؟

**Comment by radkesvat** [comment]
اره همه اینا میره روی waterwall ؛ الان درحال اتمام http2 هستش و بعدش میشه باهاش تونل کرد و فرگمنت رو دلبخواه بهش اضافه کرد یا حتی حرکت های دیگه ای که هست
