### ISSUE TITLE
اموزش نصب نسخه ۵.۴

### ISSUE THREAD

**Issue by mohamad12213** [radkesvat/ReverseTlsTunnel#338]
نسخه ۵.۴ رو چجوری میتونم نصب کنم؟ لطفا اگه کسی بلده راهنمایی کنه

**Comment by m2tts2001** [comment]
apt install unzip -y
wget https://github.com/radkesvat/ReverseTlsTunnel/releases/download/V5.4/v5.4_linux_amd64.zip
unzip v5.4_linux_amd64.zip
chmod +x RTT

**Comment by mohamad12213** [comment]
> apt install unzip -y wget https://github.com/radkesvat/ReverseTlsTunnel/releases/download/V5.4/v5.4_linux_amd64.zip unzip v5.4_linux_amd64.zip chmod +x RTT

دمت گرم دو روز بود دنبال اموزش نصبش میگشتم (:

**Comment by mohamad12213** [comment]
> apt install unzip -y wget https://github.com/radkesvat/ReverseTlsTunnel/releases/download/V5.4/v5.4_linux_amd64.zip unzip v5.4_linux_amd64.zip chmod +x RTT

الان این دستورات رو زدم با چه اسکریپتی باید اجرا کنم تانل رو؟؟؟؟
