### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by randomguy-on-internet** [radkesvat/ReverseTlsTunnel#34]
میشه یه argument دیگه هم اضافه کنید که بجای اینکه به 0.0.0.0 همیشه گوش بده بتونیم تغییرش بدیم به 127.0.0.1 که بشه با haproxy ترافیک رو بر اساس sni تغییر داد؟

من اینو پیدا کردم و میشه با تغییر و کامپایلش انجام داد ولی اگه صلاح دیدید اضافه کنید، ممنون میشم.
```nim
const listen_addr* = "0.0.0.0"
```

**Comment by radkesvat** [comment]
اضافه میشه به عنوان سوییچ اختیاری
