### ISSUE TITLE
خاموش شدن فایروال سرور

### ISSUE THREAD

**Issue by chrikman2** [radkesvat/ReverseTlsTunnel#344]
سلام و عرض ادب
بعد از نصب اسکریپت و اجرای سرویس ریورس ، فایروال سرور غیر فعال میشه روی سیستم عامل ubuntu 22 و ubuntu 24 تست شده ممنون میشم راهنمایی کنید این مشکل رو چطور حل کنم

**Comment by radkesvat** [comment]
> --keep-ufw

لازم به ذکر است غیرفعال شدن فایروال به این معنی نیست که پورت ها باز میشن روی سرور ؛ پورت ها به صورت دیفالت بسته هستن ؛ فایروال یه لایه روی پورت ها هست

**Comment by chrikman2** [comment]
ممنونم
