### ISSUE TITLE
وایرگارد udp کار نمیکنه

### ISSUE THREAD

**Issue by m0x61h0x64i** [radkesvat/ReverseTlsTunnel#352]
سلام، تانل زدم متاسفانه وایرگارد هندشیک نمیده. وایرگارد داکرایز شده و پورت و ایناش اوکی هست مستقیم اگر وصل بشم هندشیک میده

روی سرور ایران اینو زدم
RTT --iran --lport:22355 --sni:**** --password:**** --accept-udp

روی سرور خارج اینو زدم
RTT --kharej --iran-ip:**** --iran-port:22355 --toip:127.0.0.1 --toport:22355 --password:**** --sni:**** --accept-udp

داخل کلاینت پورت 22355 استفاده میشه و داکر هم به پورت 22355 udp لیسن میکنه:
docker ports => 0.0.0.0:22355->22355/udp, :::22355->22355/udp

کسی میدونه مشکل از چی میتونه باشه؟

با nginx روی ایران تانل میزنم اوکی هست ولی این تانل اوکی نیست و حالا سعی کردم با nginx ور برم درستش کنم هم بازم فایده نکرد

https://github.com/Musixal/Rathole-Tunnel/issues/22
https://github.com/Azumi67/Chisel_multipleServers/issues/43

**Comment by Arzenow** [comment]
چرا آی پی تیبله؟؟؟ معکوس کن

در تاریخ سه‌شنبه ۹ ژوئیهٔ ۲۰۲۴،‏ ۲۱:۵۴ m0x61h0x64i ***@***.***>
نوشت:
