### ISSUE TITLE
تانل از یک سرور خارج به چند سرور ایران

### ISSUE THREAD

**Issue by RezaKardoost** [radkesvat/ReverseTlsTunnel#4]
سلام. من این روش تانل رو با روش پنل به پنل تلفیق کردم و به خوبی تا الان کار کرد. یعنی outbound پنل سرور ایران رو به localhost و پورت مربوط به RTT فرستادم و تانل بین دو پنل رو با این روش انجام دادم. قبلش تانل رو با reverse ssh tunnel انجام میدادم که پینگ خیلی بالا میرفت و زیاد استیبل نبود. اما فعلا این روش به خوبی کار میکنه.
سوالی که دارم اینه که چطور میتونم یک سرور خارج رو به وند سرور ایران تانل کنم؟ آیا کار درستی هست که چند تا سرویس برای تانل در سرور خارج درست کنم که هر سرویس، RTT رو برای تانل به یک سرور ایران اجرا میکنه. ایا پرفورمنس این روش مشکلی نداره؟
یک سوال دیگه در مورد lpart در سرور ایران هست. وقتی مثلا این پارامتر رو 443 قرار بدم، پورت 443 سرور ایران listen میشه و به پورت 443 سرور خارج ارسال میشه؟ ایا نمیشه این دو تا پورت رو متفاوت گذاشت؟ یعنی پورت listen با forward متفاوت باشه؟

**Comment by radkesvat** [comment]
سوال اول ، مشکلی نداره میتونید چند تا سرور ایران رو هرطور میخواید به یک سرور خارج تونل کنید، موضوع اینه که تونل در سرور خارج به پورتی خاصی گوش نمیده چون تونل معکوس هست پس از این بابت خیالتون راحت کانفلیکت پورت روی سرور خارج غیر ممکنه توسط RTT هرطوری هم اجرا کنید


جواب سوال دوم هم دادم، دیتا به پورت مشخصی رو سرور خارج ارسال نمیشه، پس جای نگرانی نیست

**Comment by amirzare021** [comment]
@RezaKardoost 
سلام وقتت بخیر 
میتونی بگی لطفا چجوری outbound رو ست کردی رو localhost و تونل رو از rtt رد کردی ؟
