### ISSUE TITLE
مشکل عجیب روی سرور ایران

### ISSUE THREAD

**Issue by TheGhost2020** [radkesvat/ReverseTlsTunnel#43]
سلام.
2 مورد مهم هست که میخوام بگم:
1.تانل رو راه انداختم ولی فقط رو کانفیگای ریلیتی کار میکنه و با tuic یا hysteria2 جواب نمیده. راهی برای استفاده از این روش با tuic وجود داره؟
2.میخواستم مولتی پورت راه بندازم. سرور iptables نداشت. اینستالش کردم و تانل رو راه انداختم اما یکی دو ثانیه بعدش مث اینکه سرور به دیار باقی شتافت و دیگه نمیتونم با SSH بهش کانکت شم. با کنسول سایت ارایه دهنده که بهش کانکت میشم تصویری که عکسشو این پایین گذاشتم رو بهم نشون میده:
![iptables](https://github.com/radkesvat/ReverseTlsTunnel/assets/74139339/1bb0dccb-1adb-4af6-963e-1b279767f3d3)

میشه کمکم کنین بفهمم مشکل کجاست؟ شاید بقیه هم به این مشکل بر خورده باشن.

**Comment by radkesvat** [comment]
خیلی بعیده این مشکل از تونل باشه ؛ وقتی ایپی تیبل نصب نباشه فقط ارور میده و خارج میشه این سرور به بوتش آسیب رسیده

**Comment by TheGhost2020** [comment]
> خیلی بعیده این مشکل از تونل باشه ؛ وقتی ایپی تیبل نصب نباشه فقط ارور میده و خارج میشه این سرور به بوتش آسیب رسیده

آخه دقیقا بعد از اینکه iptables اینستال کردم و استارتو زدم اینطوری شد:(
سروری که گرفتم از سایت هایو هستش. یعنی مشکل از سروره؟

**Comment by radkesvat** [comment]
ایپی تیبل روش نصب نبوده ؟ سیستم عاملش  چیه ؟ ترجیها به سرور ابونتو برای تونل بسازید چون ذوشون ایپی تیبل نصب هست از قبل

**Comment by TheGhost2020** [comment]
> ایپی تیبل روش نصب نبوده ؟ سیستم عاملش چیه ؟ ترجیها به سرور ابونتو برای تونل بسازید چون ذوشون ایپی تیبل نصب هست از قبل

از اول روش نصب نبود. خودم نصب کردم. سرور رو با یه ورژن دیگه از اوبونتو (22.04) ساختم iptables هم نصب کردم تانل رو اینبار که راه انداختم بوتش مشکل نداشت ولی الان SSH از کار افتاده فقط با کنسول سایت میتونم بهش کانکت شم.

**Comment by ardalaaan** [comment]
در مورد مشکل اول من از gost استفاده کردم چون این روش گویا برای tcp هست ( هیستریا و توییک رو udp کار میکنن )
منتهی بجای kcp من udp نوشتم تا کار کرد ( تا جایی که خوندم قاعدتا باید با kcp هم کار میکرد ولی موفق نشدم )
https://v2.gost.run/en/kcp
فقط نمیدونم شانس لو رفتن و مسدود سازی ارتباط از این طریق چقدره ؟ یعنی بهتره قیدش رو بزنیم بچسبیم به همین reversetunnel و tcp ؟

**Comment by TheGhost2020** [comment]
> در مورد مشکل اول من از gost استفاده کردم چون این روش گویا برای tcp هست ( هیستریا و توییک رو udp کار میکنن ) منتهی بجای kcp من udp نوشتم تا کار کرد ( تا جایی که خوندم قاعدتا باید با kcp هم کار میکرد ولی موفق نشدم ) https://v2.gost.run/en/kcp فقط نمیدونم شانس لو رفتن و مسدود سازی ارتباط از این طریق چقدره ؟ یعنی بهتره قیدش رو بزنیم بچسبیم به همین reversetunnel و tcp ؟

پس بقیه هم همینطورین و با توییک براشون کار نکرد.
اوکی پس مشکل از طرف من نیست.
مرسی که گفتی.

**Comment by TheGhost2020** [comment]
با یکم تلاش تونستم تانل رو راه بندازم ولی نمیدونم چرا بعد از ران کردن دستور تانل با multiport و فعال شدن iptables دیگه SSH کار نمیکنه...
فقط با کنسول وبسایت میتونم به سرور ایران دسترسی پیدا کنم.
دولوپر عزیز اگه ممکنه یه نگاهی به کد های مربوط به iptables بنداز.
مرسی که به مردم کمک میکنی🌹

**Comment by radkesvat** [comment]
پورت ۲۲ را نباید داخل بازه پورت قرار بدین وگر نه نمیتونین ssh بزنین

**Comment by TheGhost2020** [comment]
> پورت ۲۲ را نباید داخل بازه پورت قرار بدین وگر نه نمیتونین ssh بزنین

پورتی که برای SSH استفاده میکنم 2280 هستش و عددی هم که برای پورت سرور ایران انتخاب میکنم همون 23-65535 هستش

**Comment by radkesvat** [comment]
tuic 
فکر نکنم چون اون udp بود تا جایی که یادمه

**Comment by TheGhost2020** [comment]
> tuic فکر نکنم چون اون udp بود تا جایی که یادمه

اوکی بازم ممنون🙏
