### ISSUE TITLE
سوال درباره پروتکل SSTP

### ISSUE THREAD

**Issue by mam4dali** [radkesvat/ReverseTlsTunnel#46]
سلام. خسته نباشید
در حال حاضر این سیستم صرفا v2ray ساپورت میکنه؟
من سعی کردم برای SSTP استفاده کنم ولی خطای CN نامعتبر میده

**Comment by radkesvat** [comment]
اینم تی سی پی هست باید کار کنه  روی پورت ۴۴۳ تونلش کردین و کار نکرد؟ بهگعد از درست تونل شدن مطعمن بودین؟ مثلا چمیدونم سایت یا پنل یا پروتوکل دیگه ای روی تونل تست کردین ببینید کار میکنه؟

**Comment by mam4dali** [comment]
> اینم تی سی پی هست باید کار کنه روی پورت ۴۴۳ تونلش کردین و کار نکرد؟ بهگعد از درست تونل شدن مطعمن بودین؟ مثلا چمیدونم سایت یا پنل یا پروتوکل دیگه ای روی تونل تست کردین ببینید کار میکنه؟

نه روی پورت دیگری بود. بله تونل درست بود و برای v2ray جواب داد.
البته من گواهینامه SSTP رو با  CN Self certificate تولید کرده بودم. با این اوصاف فکر میکنم اگر گواهینامه با CN شناخته شده (با توجه به فایل cacert.pem داخل ریلیز ویندوز) امضا بشه، احتمالا مسئله حل میشه

**Comment by radkesvat** [comment]
من sstp رو درست نمیشناسم ولی فکر میکنم فقط باید با پورت ۴۴۳ تونلش کنید توی ویکیپدیا که اینجوری میگفت...

به نظرم دیتا درست برسه به پورت مقصد باید وصل بشه ...
