### ISSUE TITLE
سوال در مورد ssh

### ISSUE THREAD

**Issue by pouriyank** [radkesvat/ReverseTlsTunnel#47]
درود و خسته نباشید
میخواستم بدونم میشه این روش رو برای پنل های ssh هم اجرا کرد ؟ یا فقط برای پنل های v2ray هست این روش؟

**Comment by radkesvat** [comment]
بله ssh هم میشه تونل کرد چون Tcp هست فقط پورت هارو توی دستور دقت کنید درست قرار بدین

**Comment by pouriyank** [comment]
> بله ssh هم میشه تونل کرد چون Tcp هست فقط پورت هارو توی دستور دقت کنید درست قرار بدین

برای تماس تصویری به مشکل نمیخوره؟و اینکه محدودیت تک کاربر جواب میده؟

**Comment by radkesvat** [comment]
احتمال زیاد مشکلی پیش نیاد ؛ ولی من خودم چون رو ssh نیستم نحوه هندل کردن یو دی پیشو نمیدونم ولی دیفالتش اینه که از تی سی پی رد کنه و اگه اینکارو کرده باشه مشکلی پیش نمیاد

**Comment by pouriyank** [comment]
تک کاربره پنل های ssh به مشکل نمیخوره؟
یا باید پنل رو روی سرور ایران اجرا کنیم تا ip هر کاربر تفکیک باشه؟

**Comment by radkesvat** [comment]
تا جایی که میدونم ssh تک کاربرش به مشکل نمیخوره چون اون بر اساس ایپی نیست بر اساش seassion هست
