### ISSUE TITLE
تغییر پورت ایران به خارج

### ISSUE THREAD

**Issue by danyalfa79** [radkesvat/ReverseTlsTunnel#5]
با درود و احترام
یک مورد برتری که توی FTT وجود داشت ولی در حال حاضر توی RTT وجود نداره به این صورت بود که من میتونستم پورت کانفیگ رو توی سرور خارج مثلا روی ۲۰۸۷ قرار بدم، بعد آدرس دامنه کانفیگ رو به آدرس دامنه سرور ایران تغییر بدم و بعد هم کانفیگ رو به یوزر بدم. اینطوری یوزر از طریق پورت ۲۰۸۷ به سرور ایران کانکت میشد، سرور ایران و خارج با پورت ۴۴۳ کانکت میشدن که کمترین قلقلک رو داره و دیتا وقتی به سرور‌خارج میرسید دوباره توسط ftt به پورت ۲۰۸۷ هدایت میشد
به این طریق نیازی به تغییر کانفیگ های طرف یوزر هم نمیبود

امیدوارم تونسته باشم کامل منظورمو برسونم، علی ای حال این قابلیت خیلی مفیدی بود که باتوجه به ریدمی rtt بنظرم دیگه توی این اپ جایگذاری نشده بود و‌ همه چی باید روی ۴۴۳ پیاده میشد

**Comment by radkesvat** [comment]
بله قابلیت مالتی پورت ؛ الان روی همون دارم کار میکنم تا چند ساعت دیگه منتشر میشه

**Comment by danyalfa79** [comment]
سپاس از پیگیریتون. برای اولین بار RTT رو امتحان کردم و میتونم بگم حداقل 20-30% پینگش نسبت به FTT بهبود داشته

ولی کماکان چیزی که مد نظر من بود رو پیاده نکرده
مثلا من برای تانل FTT، پورت های 2052 و 2087 رو استفاده میکردم و از پورت 443 هم برای انتقال اطلاعات بین دو سرور استفاده میکردم. در این بین هم از پورت های دیگه مثل 1333 برای اتصال به سرور ایرانم و صرفا دور زدن محدودیت های اینترانت استفاده کنم
صرفا به عنوان یه درخواست بنظرم جالب میشد اگر امکانش میبود که توی دستور Iran-portمیتونستیم یه پورتی خارج از بازه پورت هایی که در سرور ایران ست شده انتخاب کنیم

**Comment by radkesvat** [comment]
ببینید این تانل هم مثل FTT هست یه بازه پورت میگره و فوروارد میکرد به خارج ؛ من متوجه نشدم تقاوتشون دقیقا چیه و چه کاری رو نمیشه انجام داد یکم با جزیات بیشتر توضیح بدین ممنون میشم .
و اینکه به طور کلی الان وقتی تونل میکنید با RTT اگه پورت ۴۴۳ جزو بازه پورت باشه ؛  وقتی ایپی ایران رو با پورت ۴۴۳ باز کنید انگار ایپی خارج رو با پورت ۴۴۳ باز کردید دقیقا مثل تونل عادی ایپی تیبل

**Comment by danyalfa79** [comment]
خوب پس بذارید با کامند توضیح بدم
کامند هایی که من توی FTT استفاده میکردم برای سرور ایران:
/FTT --tunnel --lport:2000-65535 --toip:1.1.1.1 --toport:443 --sni:xxx.com --password:123ab
برای سرور خارج:
/FTT --server --lport:443 --toip:127.0.0.1 --toport 9999 --sni:xxx.com --multiport --password:123ab
توجه کنید توی FTT نیازی نبود پورتی که میخوایم برای تونل بین ایران و خارج استفاده کنیم (443) توی بازه باشه(2000-65535). درخواستم به این صورت هست که این اتفاق توی RTT هم بیوفته و بتونیم از پورتی که در بازه تعیین شده نیست، برای تانل استفاده کنیم

**Comment by radkesvat** [comment]
من این رو اضافه میکنم ؛ مثلا میگیم سرور ایران به یه پورت دیگه جدا از بازه هم گوش بده (443 مثلا) و توی سرور خارج شما میتونین این پورت رو داخل --iran-port قرار بدین و باز هم مالتی پورت را داشته باشیم ( هم پورت هایی که تو بازه هستن و هم پورت ۴۴۳

**Comment by danyalfa79** [comment]
سپاس از شما. گزینه add-port واقعا گزینه مناسبی بود که تقریبا همون چیزی که توی ذهن من بود رو پیاده میکرد و البته جای خالیش هم توی FTT بسیار حس میشد
کاش حالا که این قابلیت ادد پورت رو اضافه کردید، اجازه اضافه شدن چند تا پورت جلوی پارامتر add-port هم داده میشد

**Comment by radkesvat** [comment]
مثلا برای اضافه کردن ۳ تا پورت میتونید سه بار addport رو تکرار کنید

> --add-port:443 --add-port:444 --add-port:445
