### ISSUE TITLE
مشکل بعد از آپدیت

### ISSUE THREAD

**Issue by armintsa** [radkesvat/ReverseTlsTunnel#50]
سلام، من به این error خوردم روی سرور خارج:
Tls error, handshake failed because:
(X509DnMismatch) Issuer/subject DN mismatch in the chain (code: 55)
![Screenshot 2023-09-15 123840](https://github.com/radkesvat/ReverseTlsTunnel/assets/21049250/a06068c3-60fb-4134-974e-f57a5e050be1)

سرور ایران اکیه.
و اینکه یه سوال، زمانی که v2ray config url ایجاد میکنیم روی پنل Sanaei، آیا کاری میشه کرد که IP سرور ایران داخلش مشخص نباشه؟ خیلی خیلی ممنون

**Comment by radkesvat** [comment]
این مشکل به این دلیله که Sni داخل دستور سرور ایران یه چیز زدین ؛ داخل دستور سرور خارج یه چیز دیگه متفاوت

درمورد سوال دوم میتونید ایپی ایرانتونو بدین به دامنه و دامنه رو به عنوان آدرس کانفیگ بزارید

**Comment by armintsa** [comment]
فوق العاده
ممنون
