### ISSUE TITLE
جلوگیری از ریستارت سرویس

### ISSUE THREAD

**Issue by Sorenawr** [radkesvat/ReverseTlsTunnel#54]
سلام وقتتون بخیر باشه. توی آپدیت آخر گفتین نیازی نیست هر ۲۴ ساعت ریستارت بشه سرویس دیگه. برای اینکه دیگه ریستارت نشه باید چه تغییری توی فایل سرویس انجام بدم؟

**Comment by Sorenawr** [comment]
کل ( --terminate:24) رو بردارم یا فقط عددش؟

**Comment by ZarinNegah** [comment]
> کل ( --terminate:24) رو بردارم یا فقط عددش؟

تمام اون پارامتر بردارید
ولی باشه بهتره، اتفاق خاصی نمیافته که احساس بشه از سمت کاربرا
من خودم هر 12 ساعت سرورهامون اتومات میزنم ریبوت شن
