### ISSUE TITLE
اجرای برنامه به صورت سرویس و لود بالانس

### ISSUE THREAD

**Issue by mohamad15516** [radkesvat/ReverseTlsTunnel#59]
با سلام و احترام در حالت سرویس شدن و لود بالانس چند سرور ایران به یک سرور خارج دستور سرویس باید به چه شکل باشد؟

**Comment by mohamad15516** [comment]
خب من یه خورده ور رفتم و مشکل خودمو رفع کردم

و شما دوستانی که به این مشکل برخوردن فقط نیازه که توی سرور خارج یک سرویس جداگونه با هر اسمی برای ایپی دیگه  ایرانتون بزارن و اون سرویس جدید رو ران کنید

**Comment by Shm9220** [comment]
> خب من یه خورده ور رفتم و مشکل خودمو رفع کردم
> 
> و شما دوستانی که به این مشکل برخوردن فقط نیازه که توی سرور خارج یک سرویس جداگونه با هر اسمی برای ایپی دیگه ایرانتون بزارن و اون سرویس جدید رو ران کنید

یه راهنمایی میکنی رییس

**Comment by mohamad15516** [comment]
باید به همون روش دوباره یه سرویس بزنی با یک اسم جداگونه گفتم که دقیق بخون
