### ISSUE TITLE
کار نکردن multiport

### ISSUE THREAD

**Issue by aligoldenhat** [radkesvat/ReverseTlsTunnel#66]
سلام
موقع ران کردن سرور ایران با ملتی پورت 
کامند ران میشه ولی هیچ لاگی پرینت نمیشه.
 به این شکل 

`./RTT --iran  --lport:443-2000  --sni:splus.ir --password:123
`

```
version="3.3"
mode="iran"
listen_port=0
final_target_domain="splus.ir"
password="123"
```

هیچ لاگی بعد این پرینت نمیشه و سرور خارج
```
Connection failed because:   
TransportOsError: (111) Connection refused 
```

و بدون هیچ مشکلی روی تک پورت ۴۴۳ کار میکنه

**Comment by ZarinNegah** [comment]
اینجا بررسی کنید
حتما مشکل شما هم همین هست
https://github.com/radkesvat/ReverseTlsTunnel/issues/58#issuecomment-1721634554

**Comment by radkesvat** [comment]
اگه مشکلتون حل نشد ، چک کنید که lsof روی سیستمتون نصب هست یا نه

مثلا بزنید lsof -v ببینید میگه نصب نیست یا هست

**Comment by aligoldenhat** [comment]
سرور ایران: 
`-bash: lsof: command not found`

**Comment by aligoldenhat** [comment]
> اینجا بررسی کنید حتما مشکل شما هم همین هست [#58 (comment)](https://github.com/radkesvat/ReverseTlsTunnel/issues/58#issuecomment-1721634554)

این issue رو قبلا دیدم و رفتم ولی مشکلم حل نشد

**Comment by aligoldenhat** [comment]
> اگه مشکلتون حل نشد ، چک کنید که lsof روی سیستمتون نصب هست یا نه
> 
> مثلا بزنید lsof -v ببینید میگه نصب نیست یا هست

سرور ایران: 
`-bash: lsof: command not found`

**Comment by aligoldenhat** [comment]
> اگه مشکلتون حل نشد ، چک کنید که lsof روی سیستمتون نصب هست یا نه
> 
> مثلا بزنید lsof -v ببینید میگه نصب نیست یا هست

نصب کردم و مشکلم حل شد 
مرسی ازتون
