### ISSUE TITLE
عدم نصب سرور ایران

### ISSUE THREAD

**Issue by siavash3441** [radkesvat/ReverseTlsTunnel#71]
سلام خطا
install.sh: line 65: unzip: command not found
chmod: cannot access 'RTT': No such file or directory
finished.

در پایان نصب میده،دسترسی روت هست و سرور‌هم آپدیت کردم

**Comment by ZarinNegah** [comment]
سلام
اینو بخونید
https://github.com/radkesvat/ReverseTlsTunnel/issues/56

**Comment by siavash3441** [comment]
حل شد ممنون
