### ISSUE TITLE
سوال راجع به لود بلنسینگ

### ISSUE THREAD

**Issue by ahmad-79** [radkesvat/ReverseTlsTunnel#76]
درود
من سرور خارجم ی آیپی اصلی داره و آیپی floating و همونطور که اینجا https://github.com/radkesvat/ReverseTlsTunnel/issues/16#issuecomment-1720855391 گفتم میخوام از هر دو آیپی تانل بخوره به سمت ایران
ی راهی پیدا کردم با iptables NAT rule ترافیک outgoing ی یوزر رو از floating بدم بیرون پس وقتی ی بار تانل رو با روت ران کنم و ی بار با اون یوزر هر دو آیپی استفاده میشن

حالا سوالم ازتون اینه که لازمه برای پخش درست ترافیک همون طور که توی آموزش آوردید توی --toip کامند floating آیپی، آیپی اصلی سرور رو بذارم یا برای هردو همون 127.0.0.1 رو بذارم کافیه؟، چون همون سروره دیگه
راستش اصلا اون تیکه آموزش و دلیل اینکه چر باید آیپی سرور اول رو بدیم رو نفهمیدم, الان با اون کار سرور دومی هم ی تانل به سرور اولی میزنه و دیتایی که ایران از کاربرا بهش داده رو میده سرور اولی؟
سرور ایران بر چه اساسی ترافیک رو بین peerهایی که بهش دادیم پخش میکنه؟

ی سوال دیگه هم داشتم
وقتی تانل رو روی یوزری که ساختم ران میکنم چون روت نیست لازمه --keep-os-limit رو بذارم میشه ی توضیح بدید قضیش چیه دقیقا و اینکه کامند چه مقداری رو ست میکنه و میتونم خودم cat /proc/sys/fs/file-max رو ادیت کنم لازم نباشه اسکریپت کاری کنه؟

**Comment by radkesvat** [comment]
برای هردو ۱۲7.0.0.1 کافیه

سوال دومتون رو دقیق متوجه نشدم ولی به طور کلی سرور p2 دیتا رو تونل میکنه به سرور نهایی که p1 هست و به هسته میرسونه نه تونلی  که روی p1 هست

سرور ایران رندوم هر کانکشن رو یا میده به p1 یا p2

این رو فکرنکنم بتونید خودتون  بدون روت انجام بدین ؛‌ ولی اگه تونستید باید برنامه رو هم کامپایل کنید بگید با اینکه روت نیست دستور افزایش لیمیت رو به سیستم عامل بده و در عین حال لیمیتی خودتون میخواید رو قرار بدین

**Comment by ahmad-79** [comment]
منظورم این بود وقتی به سرور دوم آیپی سرور اول رو میدیم ی تانل هم بین سرور اولی و دومی برقرار میشه یا همون تانلی که جفتشون به سرور ایران زدن دیتا رو بینشون منتقل میکنه؟
نوع تانل چی هستش؟
