### ISSUE TITLE
قطع تانل

### ISSUE THREAD

**Issue by siavash3441** [radkesvat/ReverseTlsTunnel#80]
سلام
بعد چند ساعت تانل ارتباطش قطع یا به شدت سرعتش کم میشه،حتی چند بار سرور ایران رو تغییر دادم همین طور هست میشه لطفا کم‌کنید،منابع سرور هم نرمال هست از ۳۰ درصد نمیره بالا

**Comment by radkesvat** [comment]
چک میکنم
