### ISSUE TITLE
یه چیز عجیب 

### ISSUE THREAD

**Issue by amg9898** [radkesvat/ReverseTlsTunnel#91]
این تعداد  کل کاربر هامه هیچکس هم حذف نکردم
 مصرفشون رو ببینین
![image](https://github.com/radkesvat/ReverseTlsTunnel/assets/105120098/ec761ce2-ce2b-4062-b340-0743c830e739)

و این مصرف کل هست چرا ؟! در صورتی که بدون تانل اینطور نشده

![image](https://github.com/radkesvat/ReverseTlsTunnel/assets/105120098/19a063aa-b85b-4f07-9fc1-474914e0df46)

**Comment by amg9898** [comment]
سلام دوباره من چک کردم مصرف رو سرور هم میاد اینجا نشون میده و جالب این من رو سرور هیچ چیز جز تانل ران نکردم چرا داره این همه سند رسیو میکنه

**Comment by amg9898** [comment]
چیزی که متوجه شدم تانل داره این حجم رو سرور خارج استفاده میکنه کع مشکل نداره اما متاسفانه فوروارد میشه رو سرور ایران اون هم مصرف میکنه

سرور ایران

![image](https://github.com/radkesvat/ReverseTlsTunnel/assets/105120098/9a792bff-0378-4d41-8218-59c84aad6492)

مصرف کل سرور خارج

![image](https://github.com/radkesvat/ReverseTlsTunnel/assets/105120098/32d37b42-0c7f-4165-b0b6-a7b3d20334c7)

مصرف کلی کاربرا

![image](https://github.com/radkesvat/ReverseTlsTunnel/assets/105120098/dc65b6fd-71e6-46db-94dd-3b3d77f4c3a3)

که راحت متوجه میشن دو برابره حجم خودشون کاربرا دارن مصرف میکننن

**Comment by radkesvat** [comment]
ببینید حجمی که پنل ها نشون میدن حجم مصرفی تانل نیست حجمیه که خود هسته xray مصرف کرده ؛ مگه اینکه مثلا خلافش رو ثابت کنید به این صورت که با سرور خارج و با دستور wget یه فایل دانلود کنید و بعد ببینیم که حجمی که xui نشون داده به اندازه سایز اون فایل بالا رفته ؛ من هنوز متوجه نشدم مشکل دقیقا چیه و منطقی نیست تانل ترافیکی بیشتر از انتقال ترافیک کاربر مصرف کنه

**Comment by amg9898** [comment]
منم همیو میگم منتقی نیست میخوایین تست کنم چیزی که خودشون گفتم ازسرور هر چی مصرف شه تو پنل میزنه

**Comment by amg9898** [comment]
بخدا از دیشب تا الان کلی مصرف شده یکم دیگه یمونم کل حجم تانلم میره

**Comment by radkesvat** [comment]
با این دستور سرعت لحظه ای اپلود و دانلود سرور ایران رو مشاهده کنید

> nload


باید سرعت اپلود و دانلود تقریبا یکی باشن ورگنه چیز دیگه ای داره ترافیک جا به جا میکنه جدا از تونل

**Comment by radkesvat** [comment]
یه همچین پترنی باید باشه 
![image](https://github.com/radkesvat/ReverseTlsTunnel/assets/134321679/d7b3b842-d43d-44fc-bbed-8167df952519)

**Comment by amg9898** [comment]
ایران

![image](https://github.com/radkesvat/ReverseTlsTunnel/assets/105120098/cbea3252-4a01-48c1-bb66-a1f8d9dc6b4c)

خارج

![image](https://github.com/radkesvat/ReverseTlsTunnel/assets/105120098/691a36fd-429b-4fb3-8e68-d7adf7bcf353)

**Comment by amg9898** [comment]
من اینقدر که این زده مصرف نداشتم حتی حاصرم دسترسی بدم چک کنین

**Comment by radkesvat** [comment]
یه نکته ای درمورد تونل ها بگم شاید ندونید

سرور تونل ترافیک اینطوریه ؛ یه پکت از سمت کاربر میاد ؛ بعد همون پکت رو میده به سرور خارج
بعد پاسخش رو از سرور خارج میگیره و میده به کاربر

پس سرور تونل ۲ تا پکت دریافت کرد و دوتا پکت هم ارسال کرد در حالی که کاربر یه پکت ارسال کرد و یه پکت دریافت کرد

پس نتیجه اینه که ترافیک مصرفی سرور تونل همیشه ۲ برابر کاربره یعنی اگه کاربر یه فیلم ۱ گیگی دانلود کنه سرور تونل ۲ گیگ ترافیک مصرف کرده ؛ و دیتا سنتر ها هم پول ۲ گیگ رو میگیرند عموما

**Comment by amg9898** [comment]
خب نمیشه اینو فیکش کرده 2 نیشه اینطوری باید کلی پول ترافیک بدم که

**Comment by radkesvat** [comment]
با هر روشی تونل کنید بلا استثنا همین داستان هستش طبیعت تانل اینجوریه

**Comment by amg9898** [comment]
ممنون میشم

**Comment by radkesvat** [comment]
اولیش اینه که از دیتا سنترهایی بخرید که پول اپلود از سرور تانل نمیگیرند فکر میکنم آسیا تک و ویرا کلود اینطوری باشند اینطوری در هزینه ها صرفه جویی میشه 

دومین راه استفاده از اپلود فیک یک به ۱۰ هست ؛ در بعضی دیتا سنتر ها مثل زیرساخت اگه اپلود یک به ۱۰ داشته باشید تمام ترافیک مصرفی رایگان حساب میشه اما باید دقت کنید اپلود فیک اگه تشخیص داده بشه مشکل ساز میشه ؛ من خودم اضافه کردن اپلود فیک رو توی برنامه اپدیت تونل دارم که امروز فردا اضافه میشه

**Comment by amg9898** [comment]
منم از دیتاسنتر ها خریدم البته دراک کلود 

چجوری دیتاسنتر ها پول همون ۱ گیگ رو میدید به جای ۲ گیگ برای جای سواله

**Comment by radkesvat** [comment]
دیتا سنتر ها پول همون ۱ گیگ هم نباید بگیرند ولی خوب بوی پول به مشامشون رسیده 😀

بعضی دیتا سنتر ها توی شرایط فروششون این امکان رو گزاشتند که فقط پول ترایک دانلود سرور رو میگیرند و ترافیک اپلود سرور را رایگان قرار دادند

**Comment by amg9898** [comment]
> دیتا سنتر ها پول همون ۱ گیگ هم نباید بگیرند ولی خوب بوی پول به مشامشون رسیده 😀
> 
> بعضی دیتا سنتر ها توی شرایط فروششون این امکان رو گزاشتند که فقط پول ترایک دانلود سرور رو میگیرند و ترافیک اپلود سرور را رایگان قرار دادندش
نمیشه چند تا معرفی کنین؟

**Comment by radkesvat** [comment]
گفتم اسیا تک و ویرا کلود اینطورین تا جایی که یادمه

**Comment by amg9898** [comment]
هر چی میزنم تو گوگل ویر کلود نمیاره

**Comment by radkesvat** [comment]
https://panel.virakcloud.com/

**Comment by amg9898** [comment]
> https://panel.virakcloud.com/

اینم زنگ بزنم یا ترافیک 1 گیگ میگیره؟

**Comment by radkesvat** [comment]
همیشه سوال کنید و سرچ کنید همیشه جا های دیگه ای هم هستن

**Comment by radkesvat** [comment]
من این ایشیو رو میبندم اگه مشکل دیگه ای داشتین جدید ایجاد کنید یا همینجا ادامه بدین
