### ISSUE TITLE
3.6

### ISSUE THREAD

**Issue by realartin** [radkesvat/ReverseTlsTunnel#92]
درود مهندس اپدیت اخر رو امروز روی سرور ایران و خارج انجام دادم و خوب کار میکرد و به صورت سرویس

الان بعد چند ساعت میبینم از کار افتاده

**Comment by radkesvat** [comment]
لاگش رو میتونید بفرستید ؟ 

> journalctl -u tunnel.service -e -f

هروقت از کار افتاد این دستورو بزنید و لاگ رو بفرستید ممنون
