### ISSUE TITLE
گیج زدن تانل

### ISSUE THREAD

**Issue by danyalfa79** [radkesvat/ReverseTlsTunnel#93]
با درود
توی نسخه آخر برنامه که قرار شده کانکشن ها به صورت هوشمند بسته بشن، وقتی بعد از 10 مین عدم استفاده کلاینت، مجدد تلاش به کانکت شدن سرور میکنم حداقل چند دقیقه با سرور کل کل دارم تا متوجه بشه که من میخوام واقعا استفاده کنم و توی اون مدت تبادل دیتایی ندارم

**Comment by radkesvat** [comment]
من از دیروز که رو سرور های خودم زدم ندیدم چنین چیزیو ؛ باز بیشتر تست میکنم ولی الان رو یه سرور خالی زدم بمونه ۱۰ دقیقه ببینم بعدش چی میشه

**Comment by radkesvat** [comment]
چنین مشکلی رو ندیدم

**Comment by danyalfa79** [comment]
مشکل رو به صورت سناریوی واقعی بیان میکنم
ساعت ۸ صبح سرور استارت شده
با دیوایس A ساعت ۸:۱۵ تا ۸:۲۰ به سرور کانکت میشم و دیتا جابجا میشه
بعد از ۸:۲۰ گوشیو درحالی که vpn متصل هست میذارم کنار و میرم دنبال زندگیم
ساعت ۹:۱۰ دوباره میام سروقت گوشی، طبعا باید بلافاصله اتصال برقرار شه، درحالیکه گوشی تلاش میکنه متصل بشه ولی نمیشه. این تلاش ممکنه گاها تا ۱۰ دقیقه هم ادامه پیدا کنه و از دیروز تاحالا به نا امیدی من و تونل انجامیده!

**Comment by radkesvat** [comment]
همین سناریو رو امروز تست میکنم

**Comment by danyalfa79** [comment]
سپاس از شما
در ادامه ی همین سناریو هم بگم که از دیشب تا الان حداقل 5 بار برام اتفاق افتاده بدون هیچ دلیل خاصی، وقتی به سرور کانکتم به صورت ناگهانی کانکشنم دراپ میشه و هرچی صبر میکنم مجدد کانکشن برقرار نمیشه

**Comment by radkesvat** [comment]
یک موردی رو اگه میتونید انجام بدین و برای من بفرتسید خیلی ساده هست روی سرور داخل و خارج لطفا و خروجی دستورو بفرستید

> cd /root
> md5sum RTT

**Comment by danyalfa79** [comment]
سرور ایران:
279ed15e9894a7b3a68babc6c9112c3f
سرور خارج:
279ed15e9894a7b3a68babc6c9112c3f

**Comment by danyalfa79** [comment]
خوب من ورژن 4.1 رو هم امتحان کردم و مشکل کماکان پابرجاست
لاگ رو دقیقا از جایی که دیگه اوکی نبود قرار میدم
لاگ سرور خارج:
`
Sep 21 22:03:53 France RTT[863]: TlsHandsahke complete.
Sep 21 22:03:57 France RTT[863]: 16 x 54 x 72
Sep 21 22:04:02 France RTT[863]: 16 x 54 x 72
Sep 21 22:04:07 France RTT[863]: 15 x 54 x 73
Sep 21 22:04:07 France RTT[863]: TlsHandsahke complete.
Sep 21 22:04:08 France RTT[863]: TlsHandsahke complete.
Sep 21 22:04:08 France RTT[863]: TlsHandsahke complete.
Sep 21 22:04:12 France RTT[863]: 18 x 53 x 72
Sep 21 22:04:14 France RTT[863]: TlsHandsahke complete.
Sep 21 22:04:14 France RTT[863]: TlsHandsahke complete.
Sep 21 22:04:14 France RTT[863]: TlsHandsahke complete.
Sep 21 22:04:17 France RTT[863]: 17 x 50 x 63
Sep 21 22:04:22 France RTT[863]: 17 x 50 x 62
Sep 21 22:04:27 France RTT[863]: 16 x 49 x 61
Sep 21 22:04:32 France RTT[863]: 14 x 49 x 61
Sep 21 22:04:33 France RTT[863]: TlsHandsahke complete.
Sep 21 22:04:33 France RTT[863]: TlsHandsahke complete.
Sep 21 22:04:33 France RTT[863]: TlsHandsahke complete.
Sep 21 22:04:37 France RTT[863]: 17 x 49 x 61
Sep 21 22:04:42 France RTT[863]: 17 x 40 x 48
Sep 21 22:04:47 France RTT[863]: 17 x 39 x 47
Sep 21 22:04:52 France RTT[863]: 15 x 41 x 49
Sep 21 22:04:52 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:04:52 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:04:57 France RTT[863]: 15 x 41 x 48
Sep 21 22:04:57 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:04:57 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:00 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:00 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:01 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:01 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:02 France RTT[863]: 14 x 41 x 48
Sep 21 22:05:03 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:03 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:04 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:04 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:04 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:04 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:04 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:04 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:04 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:04 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:04 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:04 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:06 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:06 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:06 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:06 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:06 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:06 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:06 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:06 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:06 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:06 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:07 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:07 France RTT[863]: Connection to the remote peer has been lost
Sep 21 22:05:07 France RTT[863]: Tls error, handshake failed because:
Sep 21 22:05:07 France RTT[863]: Connection to the remote peer has been lost
`
ظاهرا در این نقطه سرور خارج دیگه دسترسی به سرور ایران نداره
لاگ سرور ایران:
`
Sep 21 23:07:04 Air RTT[35082]: connected to splus.ir:443
Sep 21 23:07:04 Air RTT[35082]: [Error] user connection but no peer connected yet.
Sep 21 23:07:04 Air RTT[35082]: SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Sep 21 23:07:04 Air systemd[1]: tunnelr.service: Main process exited, code=dumped, status=11/SEGV
Sep 21 23:07:04 Air systemd[1]: tunnelr.service: Failed with result 'core-dump'.
Sep 21 23:07:04 Air systemd[1]: tunnelr.service: Scheduled restart job, restart counter is at 4.
Sep 21 23:07:04 Air systemd[1]: Stopped Reverse TLS Tunnel.
Sep 21 23:07:04 Air systemd[1]: Started Reverse TLS Tunnel.
Sep 21 23:07:05 Air RTT[35280]: fs.file-max = 1000000
Sep 21 23:07:05 Air sudo[35282]:     root : TTY=unknown ; PWD=/root ; USER=root ; COMMAND=/usr/sbin/ufw disable
Sep 21 23:07:05 Air sudo[35282]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 21 23:07:06 Air RTT[35283]: Firewall stopped and disabled on system startup
Sep 21 23:07:06 Air sudo[35282]: pam_unix(sudo:session): session closed for user root
Sep 21 23:07:06 Air RTT[35270]: version="4.1"
Sep 21 23:07:06 Air RTT[35270]: mode="iran"
Sep 21 23:07:06 Air RTT[35270]: listen_port=0
Sep 21 23:07:06 Air RTT[35270]: final_target_domain="splus.ir"
Sep 21 23:07:06 Air RTT[35270]: password="Aa123"
Sep 21 23:07:06 Air RTT[35270]: terminate_secs=86400
Sep 21 23:07:06 Air RTT[35270]: terminate_secs=86400
Sep 21 23:07:06 Air RTT[35270]: host=Hostent(
Sep 21 23:07:06 Air RTT[35270]:   name: "splus.ir",
Sep 21 23:07:06 Air RTT[35270]:   aliases: @[],
Sep 21 23:07:06 Air RTT[35270]:   addrtype: "AF_INET",
Sep 21 23:07:06 Air RTT[35270]:   length: 4,
Sep 21 23:07:06 Air RTT[35270]:   addrList: @["79.127.127.35"]
Sep 21 23:07:06 Air RTT[35270]: )
Sep 21 23:07:06 Air RTT[35270]: password="Aa123"
Sep 21 23:07:06 Air RTT[35270]: password_hash="4FAD0BC2DF9B917B93047316F9F852EB8760AEA3"
Sep 21 23:07:06 Air RTT[35270]: sh1=3113786154
Sep 21 23:07:06 Air RTT[35270]: sh2=3453890362
Sep 21 23:07:06 Air RTT[35270]: sh3=3728727600
Sep 21 23:07:06 Air RTT[35270]: pool_size=16
Sep 21 23:07:06 Air RTT[35270]: Mode Iran : Ip iran  handshake: splus.ir
Sep 21 23:07:06 Air RTT[35270]: reseting iptable nat
Sep 21 23:07:06 Air RTT[35270]: Started tcp server... 0.0.0.0:2017
Sep 21 23:07:06 Air RTT[35270]: Connected client:
Sep 21 23:07:06 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57188)
Sep 21 23:07:06 Air RTT[35270]: con.port=2052
Sep 21 23:07:06 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:06 Air RTT[35270]: Connected client:
Sep 21 23:07:06 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57189)
Sep 21 23:07:06 Air RTT[35270]: con.port=2052
Sep 21 23:07:06 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:06 Air RTT[35270]: [Error] user connection but no peer connected yet.
Sep 21 23:07:06 Air RTT[35270]: Connected client:
Sep 21 23:07:06 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57190)
Sep 21 23:07:06 Air RTT[35270]: con.port=2052
Sep 21 23:07:06 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:07 Air RTT[35270]: Connected client:
Sep 21 23:07:07 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57191)
Sep 21 23:07:07 Air RTT[35270]: con.port=2052
Sep 21 23:07:07 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:07 Air RTT[35270]: [Error] user connection but no peer connected yet.
Sep 21 23:07:07 Air RTT[35270]: Connected client:
Sep 21 23:07:07 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57192)
Sep 21 23:07:07 Air RTT[35270]: con.port=2052
Sep 21 23:07:07 Air RTT[35270]: "Exception Type: " & $current_ex`gensym194.name="Exception Type: TransportOsError"
Sep 21 23:07:07 Air RTT[35270]: "Exception Message: " & $current_ex`gensym194.msg="Exception Message: (104) Connection reset by peer"
Sep 21 23:07:07 Air RTT[35270]: Connected client:
Sep 21 23:07:07 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57194)
Sep 21 23:07:07 Air RTT[35270]: con.port=2052
Sep 21 23:07:07 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:07 Air RTT[35270]: [Error] user connection but no peer connected yet.
Sep 21 23:07:07 Air RTT[35270]: Connected client:
Sep 21 23:07:07 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [37, 129, 61, 219], port: 41394)
Sep 21 23:07:07 Air RTT[35270]: con.port=2052
Sep 21 23:07:07 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:07 Air RTT[35270]: [Error] user connection but no peer connected yet.
Sep 21 23:07:07 Air RTT[35270]: Connected client:
Sep 21 23:07:07 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [ip Kharej], port: 41618)
Sep 21 23:07:07 Air RTT[35270]: con.port=443
Sep 21 23:07:07 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:07 Air RTT[35270]: Connected client:splus.ir
Sep 21 23:07:07 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [ip Kharej], port: 41630)
Sep 21 23:07:07 Air RTT[35270]: con.port=443
Sep 21 23:07:07 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:08 Air RTT[35270]: Connected client:
Sep 21 23:07:08 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57196)
Sep 21 23:07:08 Air RTT[35270]: con.port=2052
Sep 21 23:07:08 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:08 Air RTT[35270]: [Error] user connection but no peer connected yet.
Sep 21 23:07:08 Air RTT[35270]: Connected client:
Sep 21 23:07:08 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57197)
Sep 21 23:07:08 Air RTT[35270]: con.port=2052
Sep 21 23:07:08 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:08 Air RTT[35270]: Connected client:
Sep 21 23:07:08 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57199)
Sep 21 23:07:08 Air RTT[35270]: con.port=2052
Sep 21 23:07:08 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:08 Air RTT[35270]: [Error] user connection but no peer connected yet.
Sep 21 23:07:08 Air RTT[35270]: Connected client:
Sep 21 23:07:08 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57200)
Sep 21 23:07:08 Air RTT[35270]: con.port=2052
Sep 21 23:07:08 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:08 Air RTT[35270]: [Error] user connection but no peer connected yet.
Sep 21 23:07:08 Air RTT[35270]: Connected client:
Sep 21 23:07:08 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57202)
Sep 21 23:07:08 Air RTT[35270]: con.port=2052
Sep 21 23:07:08 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:08 Air RTT[35270]: [Error] user connection but no peer connected yet.
Sep 21 23:07:08 Air RTT[35270]: Connected client:
Sep 21 23:07:08 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57205)
Sep 21 23:07:08 Air RTT[35270]: con.port=2052
Sep 21 23:07:08 Air RTT[35270]: Connected client:
Sep 21 23:07:08 Air RTT[35270]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57203)
Sep 21 23:07:08 Air RTT[35270]: con.port=2052
Sep 21 23:07:08 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:08 Air RTT[35270]: connected to splus.ir:443
Sep 21 23:07:08 Air RTT[35270]: SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Sep 21 23:07:09 Air systemd[1]: tunnelr.service: Main process exited, code=dumped, status=11/SEGV
Sep 21 23:07:09 Air systemd[1]: tunnelr.service: Failed with result 'core-dump'.
Sep 21 23:07:09 Air systemd[1]: tunnelr.service: Scheduled restart job, restart counter is at 5.
Sep 21 23:07:09 Air systemd[1]: Stopped Reverse TLS Tunnel.
Sep 21 23:07:09 Air systemd[1]: Started Reverse TLS Tunnel.
Sep 21 23:07:09 Air RTT[35468]: fs.file-max = 1000000
Sep 21 23:07:09 Air sudo[35470]:     root : TTY=unknown ; PWD=/root ; USER=root ; COMMAND=/usr/sbin/ufw disable
Sep 21 23:07:09 Air sudo[35470]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 21 23:07:10 Air RTT[35471]: Firewall stopped and disabled on system startup
Sep 21 23:07:10 Air sudo[35470]: pam_unix(sudo:session): session closed for user root
Sep 21 23:07:10 Air RTT[35458]: version="4.1"
Sep 21 23:07:10 Air RTT[35458]: mode="iran"
Sep 21 23:07:10 Air RTT[35458]: listen_port=0
Sep 21 23:07:10 Air RTT[35458]: final_target_domain="splus.ir"
Sep 21 23:07:10 Air RTT[35458]: password="Aa123"
Sep 21 23:07:10 Air RTT[35458]: terminate_secs=86400
Sep 21 23:07:10 Air RTT[35458]: terminate_secs=86400
Sep 21 23:07:10 Air RTT[35458]: host=Hostent(
Sep 21 23:07:10 Air RTT[35458]:   name: "splus.ir",
Sep 21 23:07:10 Air RTT[35458]:   aliases: @[],
Sep 21 23:07:10 Air RTT[35458]:   addrtype: "AF_INET",
Sep 21 23:07:10 Air RTT[35458]:   length: 4,
Sep 21 23:07:10 Air RTT[35458]:   addrList: @["79.127.127.35"]
Sep 21 23:07:10 Air RTT[35458]: )
Sep 21 23:07:10 Air RTT[35458]: password="Aa123"
Sep 21 23:07:10 Air RTT[35458]: password_hash="4FAD0BC2DF9B917B93047316F9F852EB8760AEA3"
Sep 21 23:07:10 Air RTT[35458]: sh1=3113786154
Sep 21 23:07:10 Air RTT[35458]: sh2=3453890362
Sep 21 23:07:10 Air RTT[35458]: sh3=3728727600
Sep 21 23:07:10 Air RTT[35458]: pool_size=16
Sep 21 23:07:10 Air RTT[35458]: Mode Iran : IP Iran  handshake: splus.ir
Sep 21 23:07:10 Air RTT[35458]: reseting iptable nat
Sep 21 23:07:10 Air RTT[35458]: Started tcp server... 0.0.0.0:2094
Sep 21 23:07:11 Air RTT[35458]: Connected client:
Sep 21 23:07:11 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57241)
Sep 21 23:07:11 Air RTT[35458]: con.port=2052
Sep 21 23:07:11 Air RTT[35458]: connected to splus.ir:443
Sep 21 23:07:11 Air RTT[35458]: [Error] user connection but no peer connected yet.
Sep 21 23:07:11 Air RTT[35458]: Connected client:
Sep 21 23:07:11 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57242)
Sep 21 23:07:11 Air RTT[35458]: con.port=2052
Sep 21 23:07:11 Air RTT[35458]: "Exception Type: " & $current_ex`gensym194.name="Exception Type: TransportOsError"
Sep 21 23:07:11 Air RTT[35458]: "Exception Message: " & $current_ex`gensym194.msg="Exception Message: (104) Connection reset by peer"
Sep 21 23:07:11 Air RTT[35458]: Connected client:
Sep 21 23:07:11 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57243)
Sep 21 23:07:11 Air RTT[35458]: con.port=2052
Sep 21 23:07:11 Air RTT[35458]: Connected client:
Sep 21 23:07:11 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57244)
Sep 21 23:07:11 Air RTT[35458]: con.port=2052
Sep 21 23:07:11 Air RTT[35458]: "Exception Type: " & $current_ex`gensym194.name="Exception Type: TransportOsError"
Sep 21 23:07:11 Air RTT[35458]: "Exception Message: " & $current_ex`gensym194.msg="Exception Message: (104) Connection reset by peer"
Sep 21 23:07:11 Air RTT[35458]: Connected client:
Sep 21 23:07:11 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57246)
Sep 21 23:07:11 Air RTT[35458]: con.port=2052
Sep 21 23:07:11 Air RTT[35458]: Connected client:
Sep 21 23:07:11 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57245)
Sep 21 23:07:11 Air RTT[35458]: con.port=2052
Sep 21 23:07:11 Air RTT[35458]: connected to splus.ir:443
Sep 21 23:07:11 Air RTT[35458]: connected to splus.ir:443
Sep 21 23:07:11 Air RTT[35458]: [Error] user connection but no peer connected yet.
Sep 21 23:07:11 Air RTT[35458]: Connected client:
Sep 21 23:07:11 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57247)
Sep 21 23:07:11 Air RTT[35458]: con.port=2052
Sep 21 23:07:11 Air RTT[35458]: "Exception Type: " & $current_ex`gensym194.name="Exception Type: TransportOsError"
Sep 21 23:07:11 Air RTT[35458]: "Exception Message: " & $current_ex`gensym194.msg="Exception Message: (104) Connection reset by peer"
Sep 21 23:07:11 Air RTT[35458]: Connected client:
Sep 21 23:07:11 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57250)
Sep 21 23:07:11 Air RTT[35458]: con.port=2052
Sep 21 23:07:11 Air RTT[35458]: connected to splus.ir:443
Sep 21 23:07:11 Air RTT[35458]: Connected client:
Sep 21 23:07:11 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57251)
Sep 21 23:07:11 Air RTT[35458]: con.port=2052
Sep 21 23:07:11 Air RTT[35458]: connected to splus.ir:443
Sep 21 23:07:11 Air RTT[35458]: [Error] user connection but no peer connected yet.
Sep 21 23:07:11 Air RTT[35458]: Connected client:
Sep 21 23:07:11 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57253)
Sep 21 23:07:11 Air RTT[35458]: con.port=2052
Sep 21 23:07:11 Air RTT[35458]: connected to splus.ir:443
Sep 21 23:07:11 Air RTT[35458]: [Error] user connection but no peer connected yet.
Sep 21 23:07:12 Air RTT[35458]: connected to splus.ir:443
Sep 21 23:07:12 Air RTT[35458]: [Error] user connection but no peer connected yet.
Sep 21 23:07:12 Air RTT[35458]: Connected client:
Sep 21 23:07:12 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57254)
Sep 21 23:07:12 Air RTT[35458]: con.port=2052
Sep 21 23:07:12 Air RTT[35458]: Connected client:
Sep 21 23:07:12 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57256)
Sep 21 23:07:12 Air RTT[35458]: con.port=2052
Sep 21 23:07:12 Air RTT[35458]: connected to splus.ir:443
Sep 21 23:07:12 Air RTT[35458]: connected to splus.ir:443
Sep 21 23:07:12 Air RTT[35458]: [Error] user connection but no peer connected yet.
Sep 21 23:07:12 Air RTT[35458]: Connected client:
Sep 21 23:07:12 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57255)
Sep 21 23:07:12 Air RTT[35458]: con.port=2052
Sep 21 23:07:12 Air RTT[35458]: connected to splus.ir:443
Sep 21 23:07:12 Air RTT[35458]: [Error] user connection but no peer connected yet.
Sep 21 23:07:12 Air RTT[35458]: Connected client:
Sep 21 23:07:12 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [86, 55, 45, 12], port: 57258)
Sep 21 23:07:12 Air RTT[35458]: con.port=2052
Sep 21 23:07:12 Air RTT[35458]: connected to splus.ir:443
Sep 21 23:07:12 Air RTT[35458]: [Error] user connection but no peer connected yet.
Sep 21 23:07:12 Air RTT[35458]: Connected client:
Sep 21 23:07:12 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [ip Kharej], port: 41662)
Sep 21 23:07:12 Air RTT[35458]: con.port=443
Sep 21 23:07:12 Air RTT[35458]: Connected client:
Sep 21 23:07:12 Air RTT[35458]: address=TransportAddress(family: "IPv4", address_v4: [ip Kharej], port: 41646)
Sep 21 23:07:12 Air RTT[35458]: con.port=443
Sep 21 23:07:12 Air RTT[35458]: connected to splus.ir:443
Sep 21 23:07:12 Air RTT[35458]: connected to splus.ir:443
Sep 21 23:07:13 Air RTT[35458]: SIGSEGV: Illegal storage access. (Attempt to read from nil?)
`
به دلیلی که نمیدونم و نمیتونم متوجه بشم ظاهرا سرور ایران اتصال رو قطع میکنه
سرور خارج هم فقط از روی پورت 443 از سرور ایران دیتا میگیره. نمیدونم این حجم از پورت رندوم داستانشون چیه
و در نهایت اینکه FTT به صورت قابل قبول و بدون ایرادی بین همین دوسرور جواب میده

**Comment by danyalfa79** [comment]
به پیشنهاد مهندس sni رو تغییر دادم و مشکل حل شد
